### PR TITLE
[WIP] OpenVPN-as

### PR DESCRIPTION
**Pull request by tomholford**
This adds a one-click template for [OpenVPN Access Server](https://openvpn.net/index.php/access-server/overview.html), using [this Docker image](https://hub.docker.com/r/linuxserver/openvpn-as/).

This addresses the request in #219.

### ☑️ Self Check before Merge

- [ ] I have tested the template using the method described in README.md thoroughly
- [ ] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [ ] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
I doubt that this will work. It requires `--cap-add=NET_ADMIN` which is unavailable in Docker swarm mode: https://github.com/moby/moby/issues/25885

**Comment by tomholford** [comment]
@githubsaturn Ah, thanks for the heads up. Glad I didn't spend any more time on this!

**Comment by tomholford** [comment]
@githubsaturn Do you think something like this would work with CapRover? Seems like there is a workaround to launch a `--privileged` container within a swarm

https://alex.thom.ae/2020/02/22/openvpn-server-docker-swarm/

**Comment by githubsaturn** [comment]
Yea this is a pretty clever idea!

It's quite hacky, so it requires some time just experimenting and tweaking things to make this work properly. But other than that, the approach looks good!

**Comment by tomholford** [comment]
@githubsaturn Thanks for following up. Admittedly, this kind of thing is out of my area of expertise. But maybe if I have time in the next few weeks, I will give it a shot

**Pull request closed without merging**
