### PR TITLE
Add Seafile (official image) support

### PR DESCRIPTION
**Pull request by D3rise**
This adds Seafile support with official image: `seafileltd/seafile-mc`
- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by kgnfth** [comment]
correct me if i am wrong, but i don't see difference with #390 ?

**Comment by D3rise** [comment]
Looks like #390 used official image, but for some reason didn't set `isOfficial` flag to `true`, so in some way (except that this PR don't use `memcached`) they are identical. I think, we need to rename it to "Seafile (without memcached)"

**Comment by kgnfth** [comment]
> Looks like #390 used official image, but for some reason didn't set `isOfficial` flag to `true`, so in some way (except that this PR don't use `memcached`) they are identical. I think, we need to rename it to "Seafile (without memcached)"

Yes i agree

**Pull request merged**
