### PR TITLE
Mattermost one click app

### PR DESCRIPTION
**Pull request by Nauman3S**
mattermost one-click app with updated configs

### ☑️ Self Check before Merge

- [☑️] I have tested the template using the method described in README.md thoroughly
- [☑️] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [☑️] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [☑️] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [☑️] Icon is added as a png file to the logos directory.

## Summary

- Removed outdated mattermost one-click apps.
- Added a new mattermost one-click-app with updated configuration settings.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks for the PR!

Just one minor comment: there is not prod/dev version for this repo. Javascript is only used as a tool to build the content. Please revert changes in package.json files.

**Comment by Nauman3S** [comment]
@githubsaturn sure, done.

**Comment by githubsaturn** [comment]
Thanks! I'm not familiar with mattermost. Hence taggig @LiquidITGuy as he introduced it originally to review this.

**Comment by Nauman3S** [comment]
@LiquidITGuy kindly review this PR. Thanks.

**Comment by Nauman3S** [comment]
@githubsaturn no activity on this PR for so long.

**Comment by githubsaturn** [comment]
Yea, it's not easy to have folks spend time on free open source :) 

Please revert the changes in package.json and package-lock.json and I'll stamp

**Comment by Nauman3S** [comment]
> Yea, it's not easy to have folks spend time on free open source :)
> 
> Please revert the changes in package.json and package-lock.json and I'll stamp

I can understand that and I fully respect the OSS community.

I have reverted the changes in package.json and package-lock.json.

**Comment by jdkdev** [comment]
@Nauman3S , Hi!  Have you continued to use mattermost and have you tried upgrading to a later version like 8.0 or 9.0?

I have tried via the tag update in Caprover and both error out in the logs:
image

Any help is appreciated!

**Comment by jdkdev** [comment]
ah you are using the team edition, I will try that, thanks! I had used the enterprise edition before

**Comment by wojtishek** [comment]
@jdkdev I started with a one-click app, but each subsequent update was done using the DockerHub repository

**Pull request merged**
