### PR TITLE
Added Metabase

### PR DESCRIPTION
**Pull request by kgnfth**
#332 

### ☑️ Self Check before Merge

- [x] Icon is added as a png file to the logos directory.
- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!!

**Comment by nahtnam** [comment]
This failed for me on v0.37.6 but worked on 0.38.0-rc1

**Comment by kgnfth** [comment]
> This failed for me on v0.37.6 but worked on 0.38.0-rc1

Let me check it right now

**Comment by kgnfth** [comment]
@nahtnam i just deployed v0.37.6 without any issues
did u get any error messages so i can check

**Comment by nahtnam** [comment]
Sorry my mistake, I was missing the "v" when I copied the tag!

**Pull request merged**
