### PR TITLE
Update invalid option in environment for Chatwoot

### PR DESCRIPTION
**Pull request by pranavrajs**
- Update the default environment variables to use RAILS_ENV
- Update the base version to v1.7.2

### ☑️ Self Check before Merge

- [ ] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [ ] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
@pranavrajs this PR is marked as draft?  Are you still working on it? Or is it ready to be merged?

**Comment by pranavrajs** [comment]
@githubsaturn I updated the base version to 1.7.2. I was just double-checking the docker builds as there were some issues in the docker build yesterday. I will make it ready for review once I can confirm that build uploaded is good. I will do it a couple of hours.

**Comment by githubsaturn** [comment]
Sounds good. Thanks!

**Comment by pranavrajs** [comment]
@githubsaturn This is ready for review.

**Review by sojan-official — APPROVED** [review]

**Pull request merged**
