### PR TITLE
Feat add transfer sh

### PR DESCRIPTION
**Pull request by joshlopes**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Looks good! Please run `npm run formatter-write` to reformat

**Comment by githubsaturn** [comment]
Thanks!

**Comment by delasource** [comment]
seems to be broken

`GET https://...../api/v2/user/oneclick/template/app?appName=transfer.sh&baseDomain=https:%2F%2Foneclickapps.caprover.com 500`

**Comment by githubsaturn** [comment]
Thanks for the report! It was due to the "dot" in the name. It's fixed now https://github.com/caprover/one-click-apps/commit/f30f93855921e3e5499b9d073ae44540a3e8f01c

**Pull request merged**
