### PR TITLE
Add Remark42 application

### PR DESCRIPTION
**Pull request by paskal**
Resolves https://github.com/umputun/remark42/issues/1254, https://github.com/caprover/one-click-apps/issues/617.

### ☑️ Self Check before Merge

- [x] Tested and working
- [x] Parameterized
- [x] Icons

Screenshot:

image

### CODE REVIEW

**Comment by paskal** [comment]
Currently fails with:
```
February 6th 2022, 8:59:59.425 pm    Updating app started: test
February 6th 2022, 8:59:59.432 pm    Error: Invalid volume name: test_data
Error: Invalid volume name: test_data
    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
    at /usr/src/app/built/datastore/AppsDataStore.js:97:60
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
POST /api/v2/user/apps/appDefinitions/update 200 9.203 ms - 72
```
Something is likely wrong with environment variables, but I can't figure out which variable is to blame.

**Comment by githubsaturn** [comment]
Change this line
```diff
++            - $$cap_appname-data:/srv/var
--            - $$cap_appname_data:/srv/var

```

**Comment by paskal** [comment]
Ready for review, working as far as I can tell. I did my best to provide sane defaults.

**Comment by paskal** [comment]
@githubsaturn, would you be so kind as to review this one and let me know if anything is preventing the merge?

**Comment by githubsaturn** [comment]
I'll have a look later today or tomorrow.

**Comment by githubsaturn** [comment]
Looks good! Thanks!

**Pull request merged**
