### PR TITLE
feat: add calcom

### LINKED ISSUE #519: App Suggestion: Calendso
[Calendso](https://cal.com/) is AGPL-licensed self-hostable alternative to Calendly. [Here is their repo](https://github.com/calendso/calendso).

They already have a [Docker version](https://github.com/calendso/docker).

### PR DESCRIPTION
**Pull request by ronaldloyko**
This pull request adds the one-click-application for [Cal.com](https://cal.com).

Closes #519 

## Checks

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.
- [x] I've executed the checks if necessary by running `npm ci && npm run validate_apps && npm run formatter`
- [x] I will take responsibility addressing any issues that arises as a result of this PR (maintaining this app).

### CODE REVIEW

**Comment by githubsaturn** [comment]
Nice!!

**Comment by ThcDelux3** [comment]
I dont know excatly since which cal.com version this is the case but in the latest one this issue occurs.

When installing the calcom oneclick app you have to add an .env var manually so that the DB can be migrated:
 - `DATABASE_DIRECT_URL`

Create that variable `DATABASE_DIRECT_URL` and put the same data as you have in the variable `DATABASE_URL`

refrences:
https://github.com/calcom/docker/issues/323
https://github.com/calcom/docker/issues/329#issuecomment-1981249041

**Comment by githubsaturn** [comment]
Added the new env vars

**Comment by ThcDelux3** [comment]
Same story again...

can you please add the env var: NEXT_PUBLIC_API_V2_URL

https://github.com/calcom/docker/issues/343#issuecomment-2051871827

Example:
https://github.com/calcom/docker/blob/main/.env.example

could you also bump up the default version to  v4.4.2

**Comment by mathiasfoster** [comment]
@ThcDelux3 what should the content of NEXT_PUBLIC_API_V2_URL be?
I'm having trouble deploying this app.

**Pull request merged**
