### PR TITLE
Add Moodle LMS. (Taken from bitnami/moodle)

### PR DESCRIPTION
**Pull request by amjed-ali-k**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by amjed-ali-k** [comment]
This was previously submitted from my secondary github id without the logo. Logo added and updated now.

**Comment by githubsaturn** [comment]
Looks good! Please run formatter to format the file and we'll merge.
```
npm run formatter-write
```

**Comment by amjed-ali-k** [comment]
> 
> 
> Looks good! Please run formatter to format the file and we'll merge.
> 
> ```
> npm run formatter-write
> ```

@githubsaturn I did that. But build check is failing. 😞

**Comment by amjed-ali-k** [comment]
> 
> 
> Looks good! Please run formatter to format the file and we'll merge.
> 
> ```
> npm run formatter-write
> ```

@githubsaturn Done 👍🏼

**Comment by coffseducation** [comment]
How to upgrade or install the latest version?
Deploy method 6 does not work to upgrade. Success is given - but the version remains at 4.16.
Installing a new version by changing the tag (eg to 4.3.3) installs Moodle version 4.16.

**Pull request merged**
