### PR TITLE
MinIO - Bumped version, tweaked API name + env, hardened root user keys, added endnotes

### PR DESCRIPTION
**Pull request by nativeit**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

---
### 🆕 Changes

- [x] MinIO version bumped to `RELEASE.2023-01-18T04-36-38Z`
- [x] S3 API endpoint service named changed from `$$cap_appname-S3` to `$$cap_appname-api`
  - My reasoning was to enable users to name the main service `s3`--giving them an endpoint URL that is more consistent with generally accepted S3 storage standards--without then having the somewhat clumsy API endpoint URL `s3-s3`. This is a subjective choice, so if there is a preference for this to remain unchanged, I'm happy to change it back.
- [x] Changed default values for `Access Key` and `Secret Key` to adhere to MinIO documentation for `MINIO_ROOT_USER`. Specifically, I provided default settings of randomly generated 24-digit and 30-digit keys respectively, and modified the RegEx to allow for either empty or custom keys to be used.
- [x] Provided additional endnotes in order to:
  - Draw more attention to the required post-deployment steps
  - Provide users with authentication keys
  - Show URLs for each service
  - Provide a link to more documentation

### 🛠️ Fixed
- [x] Added `CLIENT_MAX_BODY_SIZE: 0` to API env, the image default was `20M` which prevents uploading any larger files.

---
✅ All changes have been tested and confirmed to operate as-expected.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by paluigi** [comment]
Hello,
In my case the default setting resulted in an empty value for the CLIENT_MAX_BODY_SIZE environment variable. This was creating issues and preventing Minio from working correctly after deployment.
Not sure if it was my specific issue, but I tried to deploy several times and every time I had to manually change the environment variable to make it work.
Is it possible that the zero value is somehow lost or misinterpreted when deploying?

**Comment by hosting-hs** [comment]
@nativeit 

+1 on what @paluigi Mentioned

**Comment by nativeit** [comment]
Hi @paluigi and @gigincg!

Many apologies for not seeing and responding to the original issue referenced by @paluigi. I will look into this and take any necessary steps to remedy the problem.

I still have two MinIO instances running from shortly after I submitted the PR, and don't recall having to take any additional steps to get them working. I will deploy a fresh instance today and see if I can reproduce the issue.

Just to cover all the bases, if either of you can share your system info (particularly your OS, OS version, Docker version, Caprover version, MinIO image tag, and any relevant non-sensitive env variables used at deployment, any other applications you might be using that interact with your Docker backend and/or containers) then I can also spin up a VM to match your specs to test this with. 

**Note**: The easiest way to do this is probably by running 'docker system info' from an elevated shell and copy/paste the output. I don't think any of this information is particularly sensitive, but just to be safe you may want to redact the 'NodeID', 'ClusterID', 'Node Address', and 'Manager Addresses'. 

This is my system info:

'''
Server:
 Containers: 24
  Running: 24
  Paused: 0
  Stopped: 0
 Images: 39
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: **redacted**
  Is Manager: true
  ClusterID: **redacted**
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: **redacted**
  Manager Addresses:
   **redacted**:2377
Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-21-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.484GiB
 Name: ntv02
 ID: PDNI:QV5H:5CAC:MXC5:AH3L:HRP6:RQJE:Y66F:LTAP:EWGF:K2JK:3FJJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
'''

This ultimately shouldn't take too much effort to track down and fix, I will post back here and tag you with any updates.

Thanks for taking the time to report this!

**Pull request merged**
