### PR TITLE
added Wallabag #317

### PR DESCRIPTION
**Pull request by kgnfth**
Demo https://wall.app.gocloud.fun
user:`wallabag`
pass:`wallabag`

Demo will remain until merged

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by pronoiac** [comment]
It might be worth noting that Wallabag uses email to activate accounts, and so having email setup is a dependency. Should we note this in the description? 

> Originally posted as #484.

**Comment by kgnfth** [comment]
> It might be worth noting that Wallabag uses email to activate accounts, and so having email setup is a dependency. Should we note this in the description?
> 
> > Originally posted as #484.

I created this setup as a single user.
Thats the reason i did not include the `SYMFONY__ENV__MAILER_*` variables in this setup, not everyone uses a email service.
If u don't have a email server, you can always activate the user manually from the wallabag dashboard.

**Comment by pronoiac** [comment]
Ah, I realized the user/pass from the demo above also works for the installed app. Thanks!

**Comment by kgnfth** [comment]
> Ah, I realized the user/pass from the demo above also works for the installed app. Thanks!

Yes, at the end of the installation is it also displayed. See https://github.com/caprover/one-click-apps/blob/938fe9ff2c517f8af9ed9fc3a97adb3540c89991/public/v4/apps/wallabag.yml#L66

**Pull request merged**
