### PR TITLE
Update invoiceninja One Click App

### PR DESCRIPTION
**Pull request by julianengel**
-> Bumped to latest version
-> Updated descriptions to be more clear
-> Added email env variables to main app
-> Added variables for GoCardless and enabling the banking integration

Addresses issue raised in: https://github.com/caprover/one-click-apps/issues/1047

First of all, thank you for your contribution! 😄

Please note that this repo is mostly for popular apps with thousands of stars and tens of thousands of downloads. If you'd like to add a less popular app, you can always [create your own 3rd party repo](https://github.com/caprover/one-click-apps#build-your-own-one-click-app-repository) and add your app there.

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.
- [x] I've executed the checks if necessary by running `npm ci && npm run validate_apps && npm run formatter` (If failling run the prettier: `npm run formatter-write`)
- [x] I will take responsibility addressing any issues that arises as a result of this PR (maintaining this app).

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks for the PR! Looks like formatter is failing, please run this to fix the issue:
```
npm ci && npm run formatter-write
```

**Comment by julianengel** [comment]
Hey @githubsaturn! Thanks so much :) That's weird, I ran it before doing the PR, and also ran it just now and it comes out clean. I also tested it as One Click App with the template, and it deployed without issue. 

Attached the output:
```

> caprover-one-click-apps@1.0.0 formatter-write
> prettier --write "./public/**/*.(json|yml)"

public/v4/apps/imagor-local.yml 1ms
public/v4/apps/imagor-s3.yml 3ms
public/v4/apps/imgproxy.yml 2ms
public/v4/apps/immich.yml 3ms
public/v4/apps/influxdb.yml 3ms
public/v4/apps/influxdb2.yml 2ms
public/v4/apps/invidious.yml 4ms
public/v4/apps/invoiceninja.yml 5ms
public/v4/apps/invoiceplane.yml 3ms
public/v4/apps/iredmail.yml 5ms
public/v4/apps/jellyfin.yml 2ms
public/v4/apps/jenkins.yml 2ms

```

**Comment by githubsaturn** [comment]
You've probably used  a different version of the prettifier.

Try this:
```
npm -rf node_modules
npm ci # this ensures the exact same version to be installed
npm run formatter-write

```

**Comment by julianengel** [comment]
Hey, yeah, that’s what I did. I also did a fresh pull, and ran both commands, still comes back clean.On 3 May 2024, at 16:07, Kasra Bigdeli ***@***.***> wrote:﻿
You've probably used  a different version of the prettifier.
Try this:
npm -rf node_modules
npm ci # this ensures the exact same version to be installed
npm run formatter-write

**Comment by githubsaturn** [comment]
Hmm... that's weird... Anyways, I can merge and fix it later.

**Pull request merged**
