### PR TITLE
Add Photoprism

### PR DESCRIPTION
**Pull request by vohzd**
Hello, added Photoprism & tested. All works fine.

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.
- [x] Documentation field contains a link to a page with proper explanations on environmental variables, volumes or the docker compose file.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by ckc** [comment]
Not sure which part problem, tried 20200429 and latest version tag

Deploying your photoprism
This process takes a few minutes to complete. DO NOT refresh this page and DO NOT navigate away!!!

Progress:
Parsing the template
Registering photo
Configuring photo (volumes, ports, environmental variables)
Deploying photo (might take up to a minute)

> Failed: Error: Request failed with status code 500

**Comment by githubsaturn** [comment]
@ckc 
Can you get the server's log when you're having this issue? 
```
docker service logs captain-captain --since 5m
```

**Comment by vohzd** [comment]
Also @ckc, what server are you running this on? I found that Photoprism is _really_ intensive on RAM.

**Pull request merged**
