### PR TITLE
Add directus + mysql + redis

### PR DESCRIPTION
**Pull request by JonathanDoelan**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Looks good. Just need to run `npm run formatter-write` to make sure the build passes.

**Comment by JonathanDoelan** [comment]
> Looks good. Just need to run `npm run formatter-write` to make sure the build passes.

I have to run it, or you have to run it? I don‘t know what `npm run formatter-write` is ;)

**Comment by githubsaturn** [comment]
You have to run it to make the build pass. In the repo, run:
```
npm i
npm run formatter-write
```
it automatically performs a reformat on the yaml files and makes sure they are standard.

**Comment by JonathanDoelan** [comment]
@githubsaturn  Did it via github codespaces, which was quite easy.

**Comment by githubsaturn** [comment]
Amazing! Didn't know it was possible through codespaces! It just looks like you inadvertently committed package-lock, but I just reverted it.

**Comment by JonathanDoelan** [comment]
@githubsaturn Thank you!

**Pull request merged**
