### PR TITLE
feat(*): add template for sentry

### PR DESCRIPTION
**Pull request by aldaircruz**
Hi @githubsaturn,   
Do you have any suggestion?

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Documentation field contains a link to a page with proper explanations on environmental variables, volumes or the docker compose file.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!
I have limited internet access in next 10 days. But I'll review this as soon as possible.

**Comment by githubsaturn** [comment]
@aldaircruz 

This looks exciting!

From the initial look, it looks like a relatively heavy stack... You mentioned it takes around 10 minutes to complete the installation process...

What's the minimum RAM/CPU requirements?

**Comment by aldaircruz** [comment]
@githubsaturn 
> 
> This looks exciting!
> 
> From the initial look, it looks like a relatively heavy stack... You mentioned it takes around 10 minutes to complete the installation process...
> 
> What are minimum RAM/CPU requirements?

The initial configuration took those minutes due to the  initial [database migration](https://docs.sentry.io/server/installation/docker/#running-migrations).

The documentation doesn't specify [minimum hardware requirements](https://docs.sentry.io/server/installation/#hardware) values.

The project's [README.md](https://github.com/getsentry/onpremise#minimum-hardware-requirements) mentions the need of having at least [**3GB of ram**](https://github.com/getsentry/onpremise/pull/165). Not filling this requirement may cause some errors during the initial configuration when running the database migrations.

I will add this information to instructions.start.

**Comment by MeXaaR** [comment]
You will end up with an error when integrating some stuff (i.e GitLab) if this is not filled up with the domain of the application
`"RUN echo 'system.url-prefix: \"\"' >> /etc/sentry/config.yml",`

I changed the template with the domain of the app and it works fine after that. So maybe some changes to do on that

**Comment by githubsaturn** [comment]
Is this what you're suggesting? That this line
```
"RUN echo 'system.url-prefix: \"\"' >> /etc/sentry/config.yml",
```
should be changed to something like:
```
"RUN echo 'system.url-prefix: \"my-app-name.domain.com\"' >> /etc/sentry/config.yml",
```


If this is what you are proposing, unfortunately it's not possible at the moment that we dynamically include the domain name in the template. However, it's definitely something that we can add to the template system. For example, we can introduce a new variable like `$$cap_rootdomain`. Then combined with `$$cap_appname`, it's possible to create the subdomain:
```
$$cap_appname.$$cap_rootdomain
```

**Comment by MeXaaR** [comment]
Yes exactly.

Maybe before adding this to the template system, it would be possible to add a variable to this particular app with the entire url of the app

something like this maybe
`"RUN echo 'system.url-prefix: \"$$cap_appurl\"' >> /etc/sentry/config.yml",`

**Comment by githubsaturn** [comment]
If it's necessary for this app to work, I'm okay with doing it like this for now.

**Comment by MeXaaR** [comment]
I'll try to make the changes on the weekend

**Comment by nephthys** [comment]
I filled in some parameters for the SMTP server during the installation (the parameters are in environmental variables now) but once the application is deployed, the credentials are not memorized... How to change configuration settings after installation? 

Thanks @aldaircruz for the work anyway. ;-)

**Comment by aldaircruz** [comment]
> I filled in some parameters for the SMTP server during the installation (the parameters are in environmental variables now) but once the application is deployed, the credentials are not memorized... How to change configuration settings after installation?
> 
> Thanks @aldaircruz for the work anyway. ;-)

Hi @nephthys, 

Thanks

I'm not sure why those [environment variables](https://hub.docker.com/_/sentry#environment-variable) are not working.
After the initial setup you can update those properties on the config.yml file:
https://docs.sentry.io/server/config/

**Comment by githubsaturn** [comment]
FYI - `$$cap_root_domain` is now available in one-click apps (v2) as of CapRover 1.5.1

**Comment by dg-otrs** [comment]
> > I filled in some parameters for the SMTP server during the installation (the parameters are in environmental variables now) but once the application is deployed, the credentials are not memorized... How to change configuration settings after installation?
> > Thanks @aldaircruz for the work anyway. ;-)
> 
> Hi @nephthys,
> 
> Thanks,
> 
> I'm not sure why those [environment variables](https://hub.docker.com/_/sentry#environment-variable) are not working.
> After the initial setup you can update those properties on the config.yml file:
> https://docs.sentry.io/server/config/

The issue seems the initial setup of the One Click App:
https://github.com/caprover/one-click-apps/blob/master/public/v2/apps/sentry.json#L75-L80

This will overwrite the ENV everytime.

After doing:
modg@captain ~ $ docker exec -it --user root 8a4c85e78b1c bash
root@sentry:/# cat /etc/sentry/config.yml
auth.allow-registration: false
beacon.anonymous: true
mail.from: ""
mail.host: ""
mail.password: ""
mail.port: 465
mail.use-tls: true
mail.username: ""
system.admin-email: ""
system.url-prefix: ""
root@sentry:/# echo '' > /etc/sentry/config.yml # make this as presistant volume, so that it wont get overwritten
root@sentry:/#

And setting up the ENV variable within the Caprover App all is good. Keep in mind to set them also for cron and worker App.

Cheers

Dennis

P.S. The system url prefix should be set correctly during the One Click App setup or not be filled empty! This occurs into the issue that the DSN is not set.

**Pull request merged**
