### PR TITLE
✨ Added Mastodon

### PR DESCRIPTION
**Pull request by kgnfth**
Demo: https://mastodon.app.gocloud.fun

Edit: i got permission issue when trying to upload a profile picture in this mastodon instance
but i fixed it by running `chown -R 991:991 /var/lib/docker/volumes/captain--mastodon-system`
https://github.com/tootsuite/documentation/pull/596/files

Should i document this in this template ?
and if by changing the default user folder owner will this affect caprover ?

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by kgnfth** [comment]
#200

**Comment by githubsaturn** [comment]
For the `chown` command, can you try augmenting the CMD line, i.e.:
```
CMD rm -f /mastodon/tmp/pids/server.pid; bundle exec rails db:setup; chown -R 991:991 /mastodon/public/system; bundle exec rails s -b 0.0.0.0 -p 3000
```

**Comment by kgnfth** [comment]
> For the `chown` command, can you try augmenting the CMD line, i.e.:
> 
> ```
> CMD rm -f /mastodon/tmp/pids/server.pid; bundle exec rails db:setup; chown -R 991:991 /mastodon/public/system; bundle exec rails s -b 0.0.0.0 -p 3000
> ```

I will try now

**Comment by githubsaturn** [comment]
> > For the `chown` command, can you try augmenting the CMD line, i.e.:
> > ```
> > CMD rm -f /mastodon/tmp/pids/server.pid; bundle exec rails db:setup; chown -R 991:991 /mastodon/public/system; bundle exec rails s -b 0.0.0.0 -p 3000
> > ```
> 
> I will try now
> @githubsaturn
> Just tested it but it does not work
> Also running the command inside the container gives the following error
> `chown: changing ownership of 'public/system': Operation not permitted`

Looking at their dockerfile, looks like the [USER is not root](https://github.com/tootsuite/mastodon/blob/master/Dockerfile#L134). So that's why it doesn't work. 

Alternatively, you can just point out this quirk in instructions.

**Comment by kgnfth** [comment]
> > > For the `chown` command, can you try augmenting the CMD line, i.e.:
> > > ```
> > > CMD rm -f /mastodon/tmp/pids/server.pid; bundle exec rails db:setup; chown -R 991:991 /mastodon/public/system; bundle exec rails s -b 0.0.0.0 -p 3000
> > > ```
> > 
> > 
> > I will try now
> > @githubsaturn
> > Just tested it but it does not work
> > Also running the command inside the container gives the following error
> > `chown: changing ownership of 'public/system': Operation not permitted`
> 
> Looking at their dockerfile, looks like the [USER is not root](https://github.com/tootsuite/mastodon/blob/master/Dockerfile#L134). So that's why it doesn't work.
> 
> Alternatively, you can just point out this quirk in instructions.

Done

its 12pm here
🎇🎉🎇🎉 Happy New Year 🎇🎉🎇🎉

**Comment by githubsaturn** [comment]
Thanks, and Happy New Years!

**Comment by somnathrakshit** [comment]
Can you please add an example input for these variables? It is hard to understand what kind of input those fields require?
https://github.com/caprover/one-click-apps/blob/5006081dc44e3c610c27f739c55525eb942ac2cf/public/v4/apps/mastodon.yml#L187

**Comment by kgnfth** [comment]
> Can you please add an example input for these variables? It is hard to understand what kind of input those fields require?
> 
> https://github.com/caprover/one-click-apps/blob/5006081dc44e3c610c27f739c55525eb942ac2cf/public/v4/apps/mastodon.yml#L187

If your mail server configuration requires tls, set to `true `otherwise to `false`

**Pull request merged**
