### PR TITLE
Update Ghost to v5 breaking changes

### PR DESCRIPTION
**Pull request by matbgn**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by somnathrakshit** [comment]
Unable to use Ghost 5. Getting the error below:
```/opt/bitnami/scripts/ghost/entrypoint.sh: exec format error```

**Comment by githubsaturn** [comment]
@somnathrakshit - what CPU arch you're running on? Ghost is only compatible with amd64 - doesn't work on arm

image

**Comment by somnathrakshit** [comment]
Thank you, that is indeed the problem :(

**Comment by lexoyo** [comment]
Hello
For the DB container (mysql) to work I had to find the persistant storage on my vps and `sudo chown -R 1001:1001 /path/`
Also now the ghost container is crashing with `An error occurred while installing Ghost`
Has anyone experienced this? Thx :)

```
2024-10-14T10:11:30.801684548Z ghost 10:11:30.80 INFO  ==> 
2024-10-14T10:11:30.804338437Z ghost 10:11:30.80 INFO  ==> Welcome to the Bitnami ghost container
2024-10-14T10:11:30.808388278Z ghost 10:11:30.80 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
2024-10-14T10:11:30.812139979Z ghost 10:11:30.81 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
2024-10-14T10:11:30.815903521Z ghost 10:11:30.81 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
2024-10-14T10:11:30.820316703Z ghost 10:11:30.81 INFO  ==> 
2024-10-14T10:11:30.829904755Z ghost 10:11:30.82 INFO  ==> Configuring libnss_wrapper
2024-10-14T10:11:30.866949652Z ghost 10:11:30.86 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
2024-10-14T10:11:30.940578268Z ghost 10:11:30.93 INFO  ==> Ensuring Ghost directories exist
2024-10-14T10:11:30.952156282Z ghost 10:11:30.95 INFO  ==> Trying to connect to the database server
2024-10-14T10:11:31.018066106Z ghost 10:11:31.01 INFO  ==> Configuring database
2024-10-14T10:11:31.093445501Z ghost 10:11:31.09 INFO  ==> Setting up Ghost
2024-10-14T10:11:33.051272515Z ghost 10:11:33.05 INFO  ==> Configuring Ghost URL to https://ghost.silex.me
2024-10-14T10:11:33.124951525Z ghost 10:11:33.12 INFO  ==> Configuring SMTP settings
2024-10-14T10:11:33.572168105Z ghost 10:11:33.57 INFO  ==> Passing admin user creation wizard
2024-10-14T10:11:33.586194687Z ghost 10:11:33.58 INFO  ==> Starting Ghost in background
2024-10-14T10:11:48.781324406Z ghost 10:11:48.78 ERROR ==> An error occurred while installing Ghost
```

**Pull request merged**
