### PR TITLE
iRedMail: Fix spelling

### PR DESCRIPTION
**Pull request by kaaax0815**
I just fixed the spelling of an ENV Var

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by paluigi** [comment]
Hello, trying to install this One Click app I get the following error:
```
Failed: Error: {"code":1,"message":"The command '/bin/sh -c echo \"if [\\\"$ADMIN_VERSION\\\" != \\\"NoChange\\\" && \\\"$ADMIN_VERSION\\\" != \\\"\\$(ls /opt/www/ | grep 'iRedAdmin-' | cut -d'-' -f2)\\\"]; then wget -c -q https://github.com/iredmail/iRedAdmin/archive/$ADMIN_VERSION.tar.gz && tar xzf $ADMIN_VERSION.tar.gz -C /opt/www && rm -f $ADMIN_VERSION.tar.gz && cp -R -f /opt/www/iRedAdmin-$ADMIN_VERSION/* /opt/www/iredadmin && sleep 1; rm -r /opt/www/iRedAdmin-$ADMIN_VERSION; fi\" >> build.sh' returned a non-zero code: 1"} The command '/bin/sh -c echo "if [\"$ADMIN_VERSION\" != \"NoChange\" && \"$ADMIN_VERSION\" != \"\$(ls /opt/www/ | grep 'iRedAdmin-' | cut -d'-' -f2)\"]; then wget -c -q https://github.com/iredmail/iRedAdmin/archive/$ADMIN_VERSION.tar.gz && tar xzf $ADMIN_VERSION.tar.gz -C /opt/www && rm -f $ADMIN_VERSION.tar.gz && cp -R -f /opt/www/iRedAdmin-$ADMIN_VERSION/* /opt/www/iredadmin && sleep 1; rm -r /opt/www/iRedAdmin-$ADMIN_VERSION; fi" >> build.sh' returned a non-zero code: 1
```
The app is visible in Caprover dashboard, but it is NOT deployed. How can I help with debug?

**Comment by kaaax0815** [comment]
Are there no other errors, not more context why this issue occurs?

**Comment by paluigi** [comment]
Nothing I can find in the logs. In the deployment tab the image is marked as "failed deploy".
I tried to install on an Ampere VM in Oracle Cloud, with 1 CPU and 6Gb of RAM.

**Comment by kaaax0815** [comment]
I don't know why this happens but the docker image this is based on is not production ready and fails often. So I wouldn't recommend to use this

**Pull request merged**
