### PR TITLE
Add GOST (GO Simple Tunnel) v2 & v3

### PR DESCRIPTION
**Pull request by amirsaam**
### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.
- [x] I've executed the checks if necessary by running `npm ci && npm run validate_apps && npm run formatter` (If failling run the prettier: `npm run formatter-write`)
- [x] I will take responsibility addressing any issues that arises as a result of this PR (maintaining this app).

### CODE REVIEW

**Comment by amirsaam** [comment]
I'll appreciate any help to change the base image from ubuntu to alpine in order to significantly reduce the container size of the app

**Comment by githubsaturn** [comment]
Build is failing. Make sure the file extensions are `.yml` - You can manually run validator and formatter to make sure the build passes.

**Comment by amirsaam** [comment]
@githubsaturn that was my mistake, fixed it.

**Comment by githubsaturn** [comment]
Build is still failing. Make sure to run `npm run formatter-write`  and it'll take care of formatting.

**Comment by amirsaam** [comment]
@githubsaturn build should be fixed by now, sorry about the being a newbie

**Comment by githubsaturn** [comment]
Thanks!

**Pull request merged**
