### PR TITLE
Chore: Update chatwoot config

### PR DESCRIPTION
**Pull request by sojan-official**
### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/1031

**Comment by githubsaturn** [comment]
Thanks

**Comment by githubsaturn** [comment]
@sojan-official 
It's been reported in our Slack channel that Chatwoot isn't working. Not sure if it's related to this PR. But you probably want to look into it. This is from a brand new installation using the one click app template:

image

```
2020-08-09T12:58:42.170949636Z [f4bbba10-956e-41a4-9b7a-672ffdf801fb] app/controllers/dashboard_controller.rb:11:in `set_global_config'
2020-08-09T12:59:38.102656299Z I, [2020-08-09T12:59:38.102460 #1] INFO -- : [eb07639f-ebbb-4608-a128-20ca665ebdeb] Started GET "/" for 10.0.1.5 at 2020-08-09 12:59:38 +0000
2020-08-09T12:59:38.103569005Z I, [2020-08-09T12:59:38.103379 #1] INFO -- : [eb07639f-ebbb-4608-a128-20ca665ebdeb] Processing by DashboardController#index as HTML
2020-08-09T12:59:38.106066623Z I, [2020-08-09T12:59:38.105959 #1] INFO -- : [eb07639f-ebbb-4608-a128-20ca665ebdeb] Completed 500 Internal Server Error in 2ms (ActiveRecord: 1.1ms | Allocations: 314)
2020-08-09T12:59:38.107669634Z F, [2020-08-09T12:59:38.107455 #1] FATAL -- : [eb07639f-ebbb-4608-a128-20ca665ebdeb] 
2020-08-09T12:59:38.107690334Z [eb07639f-ebbb-4608-a128-20ca665ebdeb] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR: relation "installation_configs" does not exist
2020-08-09T12:59:38.107696734Z LINE 8: WHERE a.attrelid = '"installation_configs"'::regclass
2020-08-09T12:59:38.107701234Z ^
2020-08-09T12:59:38.107705134Z ):
2020-08-09T12:59:38.107708934Z [eb07639f-ebbb-4608-a128-20ca665ebdeb] 
2020-08-09T12:59:38.107712934Z [eb07639f-ebbb-4608-a128-20ca665ebdeb] app/models/installation_config.rb:20:in `block in <class:InstallationConfig>'
2020-08-09T12:59:38.107717334Z [eb07639f-ebbb-4608-a128-20ca665ebdeb] lib/global_config.rb:41:in `db_fallback'
2020-08-09T12:59:38.107721334Z [eb07639f-ebbb-4608-a128-20ca665ebdeb] lib/global_config.rb:32:in `load_from_cache'
2020-08-09T12:59:38.107725234Z [eb07639f-ebbb-4608-a128-20ca665ebdeb] lib/global_config.rb:12:in `block in get'
2020-08-09T12:59:38.107729035Z [eb07639f-ebbb-4608-a128-20ca665ebdeb] lib/global_config.rb:11:in `each'
2020-08-09T12:59:38.107732935Z [eb07639f-ebbb-4608-a128-20ca665ebdeb] lib/global_config.rb:11:in `get'
2020-08-09T12:59:38.107736835Z [eb07639f-ebbb-4608-a128-20ca665ebdeb] app/controllers/dashboard_controller.rb:11:in `set_global_config'
```

**Comment by sojan-official** [comment]
@githubsaturn  Thanks for letting us know. We will take a look and get back with a fix.

**Pull request merged**
