### PR TITLE
Add Whoops Monitor

### PR DESCRIPTION
**Pull request by danielrataj**
Please add Whoops Monitor to one-click apps. Thank you :-)
https://github.com/whoopsmonitor/whoopsmonitor

### ☑️ Self Check before Merge

- [ ☑️ ] I have tested the template using the method described in README.md thoroughly
- [ ☑️ ] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [ ☑️ ] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [ ☑️ ] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [☑️] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by greggameplayer** [comment]
@danielrataj there is a problem with the admin password on the monitor which doesn't want to be the application password entered in the template

**Comment by greggameplayer** [comment]
image

**Comment by greggameplayer** [comment]
Okay, no it's good it was just because i have changed the encrypt key and it wasn't matching the required length

**Comment by githubsaturn** [comment]
Thanks!

**Comment by uhlhosting** [comment]
@githubsaturn this is another app that is not properly working nor has been tested if this is the case. So the app seems to fail to properly integrate the services. First the fact that the api link is not self generated, second the main apps seems to fail to connect to mongo db, while then each of the containers have plenty of log issues. This app is either updated by @danielrataj or should be removed meanwhile.

the app presents first url: http://uptime.uhl.cloud/ after install, that URL hits 502. It fails to properly explain anywhere the link between API and the app itself. It simply needs updates. while it seems to be working on https://uptime-monitor.uhl.cloud/#/ after adding the api url with same address. yet that is against the URL shown immediately after install.

**Comment by uhlhosting** [comment]
```
2023-04-20T09:41:27.548269499Z wait-for-it.sh: waiting 15 seconds for mongo:27017
2023-04-20T09:41:31.555459017Z nc: bad address 'mongo'
2023-04-20T09:41:36.562454252Z nc: bad address 'mongo'
2023-04-20T09:41:41.568373394Z nc: bad address 'mongo'
2023-04-20T09:41:42.541177473Z wait-for-it.sh: timeout occurred after waiting 15 seconds for mongo:27017
2023-04-20T09:41:42.957869935Z
2023-04-20T09:41:42.957892821Z > api@1.0.0 start
2023-04-20T09:41:42.957896711Z > NODE_ENV=production node app.js
2023-04-20T09:41:42.957899427Z
2023-04-20T09:41:44.245728839Z 2023-04-20T09:41:44.243Z error: A hook (`bull`) failed to load!
2023-04-20T09:41:44.249341665Z 2023-04-20T09:41:44.248Z error: Failed to lift app: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined {"code":"ERR_INVALID_ARG_TYPE"}
2023-04-20T09:41:44.334960532Z 2023-04-20T09:41:44.334Z error: A hook (`orm`) failed to load!
2023-04-20T09:41:55.976825250Z wait-for-it.sh: waiting 15 seconds for mongo:27017
2023-04-20T09:41:59.982529189Z nc: bad address 'mongo'
2023-04-20T09:42:04.989106292Z nc: bad address 'mongo'

```

**Pull request merged**
