### PR TITLE
Invoice Ninja

### PR DESCRIPTION
**Pull request by r-t-k**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Documentation field contains a link to a page with proper explanations on environmental variables, volumes or the docker compose file.

### CODE REVIEW

**Comment by r-t-k** [comment]
This adaptation from their docker-compose is quirky one, so if anyone wants to help make better for the caprover ecosystem, please do. The biggest hurdle I hit was needing to modify the app's nginx container's nginx.conf after the app is deployed to properly serve it.

**Comment by githubsaturn** [comment]
Thanks for the PR. 
- `v1` directory is deprecated and no longer supported, please remove the changes you made to this directory.
- For `nginx.conf` file you can use `dockerfileLines` property in the one click app json to build a custom nginx image. You can copy the file via `ADD https://.....nginx.conf /to/path` command.
Use a URL like this: https://raw.githubusercontent.com/invoiceninja/dockerfiles/7a45036c72626d67d7dd121aa81df1cee5973ac3/docker-compose/nginx.conf


that doesn't change as they update their repo.

**Comment by r-t-k** [comment]
Can you think of a way to dynamically place the srv-captain--$$cap_appname in the nginx conf? if we can solve that then this app will be pretty smooth setting up.

**Comment by githubsaturn** [comment]
Yes, it's possible, but requires some interesting bash commands. The idea is to save the app name in an environmental variable, then when the image starts, use the environmental variable to replace the template in the nginx config. There's actually an example of this within CapRover project:

https://github.com/caprover/nginx-reverse-proxy/

**Comment by githubsaturn** [comment]
Closing as stale - feel free to reopen.

**Comment by thomascenni** [comment]
Hello, I am really interested in reopening this PR, I think Invoiceninja is a web app very useful to many freelancers.

**Comment by githubsaturn** [comment]
@thomascenni 

Feel free to reopen. You can start from here: https://github.com/invoiceninja/dockerfiles/wiki/docker-compose-with-nginx

**Comment by thomascenni** [comment]
@githubsaturn 
Looking at your previous comments, is it possible to do something like this in Caprover "dockerfileLines":

FROM nginx:1.19.3-alpine
ADD https://raw.githubusercontent.com/invoiceninja/dockerfiles/master/config/nginx/in-vhost.conf /etc/nginx/conf.d/
CMD ["sed", "-i", "'s/fastcgi_pass app:9000;/fastcgi_pass $$cap_appname:9000;/g'", "/etc/nginx/conf.d/in-vhost.conf"]

So the idea is to change in the official vhost file the app with $$cap_appname (or srv-captain--$$cap_appname).

**Comment by githubsaturn** [comment]
Yes, you're definitely on the right track! You **may** have to fiddle a bit with the `CMD` line, like using `"sh","-c" pattern, but it's definitely on the right track!

**Comment by thomascenni** [comment]
Thanks, I am really on track but I need some more help.
Here a 90% working template, using RUN instead of CMD for sed:

https://gist.github.com/thomascenni/d2e68eb54484f8d9bb797e9a0c2d296d

The problem now is that all my environment variables that are in $$cap_appname are not "seen" by the nginx server which is $$cap_appname-server; I tried to add them to ngnix section, but when I run the nginx server I come across the InvoiceNinja application setup, which means that these variables are not used:

Screen Shot 2020-10-31 at 18 48 10

Host is for sure not localhost, because I defined it as srv-captain--$$cap_appname-db.
Any hints?
I really appreciate your support @githubsaturn 
Thomas

**Comment by githubsaturn** [comment]
> The problem now is that all my environment variables that are in $$cap_appname are not "seen" by the nginx server which is $$cap_appname-server;

I don't understand this. What env var you want to be available in your nginx container? And why?

**Comment by thomascenni** [comment]
No env var should be available in nginx container, but I do not understand why the application setup is not able to read and use the env var correctly defined.

**Comment by githubsaturn** [comment]
I'm not familiar with InvoiceNinja, but by the looks of it, your configs are correct.

**Comment by native-it** [comment]
I am not a professional developer, so please pardon me if I have missed anything or don't quite hit the target. That said, I am very keen on seeing this completed, and will do my best to contribute productively.

Simply using an unrelated shell, I created the /etc/nginx/conf.d/in-vhost.conf file using your link in https://gist.github.com/thomascenni/d2e68eb54484f8d9bb797e9a0c2d296d#file-invoiceninja5-yml, and then manually ran sed from line 22:

`
# wget https://raw.githubusercontent.com/invoiceninja/dockerfiles/master/config/nginx/in-vhost.conf /etc/nginx/conf.d/
# sed -i 's/app:9000/srv-captain--$$cap_appname:9000/g' /etc/nginx/conf.d/in-vhost.conf
`

The resulting change doesn't seem to be what you're looking for. It matched on line 17 "fastcgi_pass app:9000:" and changed it to "fastcgi_pass srv-captain--$$cap_appname:9000;" while leaving the server_name untouched.

<details>
<summary>Original in-vhost.conf</summary>

`server {
    listen 80 default_server;
    server_name _ in.localhost;

    root /var/www/app/public/;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    }
}`

</details>

<details>
<summary>Changed in-vhost.conf (see fastcgi_pass under location ~ \.php$</summary>

`server {
    listen 80 default_server;
    server_name _ in.localhost;

    root /var/www/app/public/;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass srv-captain--$$cap_appname:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    }
}`

</details>

**Comment by thomascenni** [comment]
Hi @fi0, according to InvoiceNinja team member answer (see https://github.com/invoiceninja/dockerfiles/issues/206), the DB fields are only hints and are not read from environment variables.
So I think it's pretty useless to develop a one-click-app where at the end you'll need to enter manually all the information to setup the application.

**Comment by githubsaturn** [comment]
@thomascenni  - looking at the response in the comment you posted, looks like you can just use:
```
      DB_HOST1=db
      DB_USERNAME1=ninja
      DB_PASSWORD1=ninja
      DB_DATABASE1=ninja
```

Notice the "`1`" suffix in the env vars

**Comment by thomascenni** [comment]
@githubsaturn 
Yes, I noticed the "1" suffix, but even with this modification the env var are not read during the setup.
Also to have a 100% working app, the "server_name" directive in nginx must be solved.

**Comment by dantosXD** [comment]
Any progress with getting this to work as a one click app?

**Comment by githubsaturn** [comment]
Done in https://github.com/caprover/one-click-apps/pull/406

**Pull request closed without merging**
