### PR TITLE
Update Fider App

### PR DESCRIPTION
**Pull request by aqidd**
- Update fider env
- Using latest fider as default

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by lexoyo** [comment]
Hi @aqidd 
Great to see fider here :)) (i discovered it because it is here actually ;)
Would you add the database like it is done with other apps?
Or maybe you could give me instructions on how to add the DB by hand?

**Comment by aqidd** [comment]
Hi @lexoyo , to add DB manually just add this env variable

DATABASE_URL=<postgres-connection-string>

**Comment by lexoyo** [comment]
That makes sense thank you

**Pull request merged**
