### PR TITLE
feat: add mixpost

### PR DESCRIPTION
**Pull request by ronaldloyko**
This pull request adds the one-click-application for [Mixpost](https://mixpost.app)

## Checks

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by ronaldloyko** [comment]
Hi @githubsaturn 

Sorry, I just got to know that now only more popular apps are accepted.
The project is relatively new and has only 275 stars and 272 image pulls so far.

Feel free to reject and close the PR.

**Comment by ronaldloyko** [comment]
Thank you, I suggest to merge it.

I believe this app has great potential because as far as I know it's the only self-hosted and open source social media management app as an alternative to Hootsuite, Buffer, etc.

**Comment by jfmadridc** [comment]
hi @ronaldloyko i was really happy to see mixpost in caprover

however i tried v1.2.0 as it has support for arm architecture but even after a successful build when i log in with the generated user and password, 

it redirects to the homepage fine, but no button menu or anything seems to do anything when i click it

none of the settings, create post, add account etc works, not even 

i know you are not a mixpost developer, but as i am new to docker and caprover in general don't know how to fix it, maybe is an Environmental Variable that changed between the v1.1.3  and v1.2.0

thanks in advance for any help you can provide, keep up the great apps

**Comment by ronaldloyko** [comment]
Hi @jfmadridc 

Have you been able to fix the problem in the meantime?

Otherwise I try to help where I can.
I would need more information, such as the error messages that occur.

**Comment by jfmadridc** [comment]
hi @ronaldloyko thanks for checking back,

i just deployed version 1.3.1.0, but the same behavior is present nothing happens when I click anything, i checked the chrome console and see the following error
```app.a891c0b4.js:4 Mixed Content: The page at 'https://mix.*****.com/mixpost' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mix.*****.com/mixpost/accounts'. This request has been blocked; the content must be served over HTTPS.```

seems to be a problem with HTTP 
every button or link seems to be using HTTP that's why the browser blocks it, 

any idea how to fix it? or maybe is an environment setting?

**Comment by ronaldloyko** [comment]
@jfmadridc 

Perfect, thanks for the feedback.
I will include a hint about HTTPS in the instructions.

**Pull request merged**
