### PR TITLE
Foswiki with Solr added.

### PR DESCRIPTION
**Pull request by dignin**
Added Tempalte File for Foswiki.

First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [ x ] I have tested the template using the method described in README.md thoroughly
- [ x ] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started. Some program changes must still be done manually. These are well described in the Ending statement.
- [ x ] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version. This tag is not dynamic in our project.
- [ x ] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [ x ] Icon is added as a png file to the logos directory.
- [ x ] Documentation field contains a link to a page with proper explanations on environmental variables, volumes or the docker compose file.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Please review the check list. Specially :
>  I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version. This tag is not dynamic in our project.

**Comment by dignin** [comment]
Is this a no go. I said this Tag is Good Version and is stable. 
    	
    	

    	Get Outlook for iOS
    
  




On Sun, May 3, 2020 at 5:49 PM +0200, "Kasra Bigdeli" <notifications@github.com> wrote:















Please review the check list. Specially :



I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version. This tag is not dynamic in our project.

**Comment by githubsaturn** [comment]
Correct - we will never want to use `latest` tag. Since this is a dynamic tag. Latest tag today is referring to version `1.2`, but next month it may refer to version `1.3` and maybe in that version there is a required environmental variable that needs to be set in order for app to work. In that case, all of a sudden this one click app stops working without anybody making any changes. 

The purpose of avoid latest tag is that we want to make sure that this one click app remains stable even if they release a new version.

**Comment by dignin** [comment]
Is everything else ok. We have a lengthy list of afterwork due to the requirements of the software that we will work out in new versions. But I throughly tested the directions. 
    	
    	

    	Get Outlook for iOS
    
  




On Sun, May 3, 2020 at 6:07 PM +0200, "Kasra Bigdeli" <notifications@github.com> wrote:















Correct - we will never want to use latest tag. Since this is a dynamic tag. Latest tag today is referring to version 1.2, but next month it may refer to version 1.3 and maybe in that version there is a required environmental variable that needs to be set in order for app to work. In that case, all of a sudden this one click app stops working without anybody making any changes.


The purpose of avoid latest tag is that we want to make sure that this one click app remains stable even if they release a new version.

**Comment by githubsaturn** [comment]
Yea everything else if fine. The only other thing that I noticed is that the image is coming from a non-official source. Can you please add this to the `instructions.start` ? Just outlining that the the source of the image? This is to ensure that we don't provide a false advertisement for unofficial resources due to their inherit security risks.

**Comment by dignin** [comment]
Actually he’s the official maintainer. Should I habe him rename the repo?
    	
    	

    	Get Outlook for iOS
    
  




On Sun, May 3, 2020 at 6:35 PM +0200, "Kasra Bigdeli" <notifications@github.com> wrote:















Yea everything else if fine. The only other thing that I noticed is that the image is coming from a non-official source. Can you please add this to the instructions.start ? Just outlining that the the source of the image? This is to ensure that we don't provide a false advertisement for unofficial resources due to their inherit security risks.

**Comment by githubsaturn** [comment]
Yes please! It needs to go to the main org package: https://github.com/foswiki

**Comment by githubsaturn** [comment]
Closing as stale - feel free to reopen.

**Pull request closed without merging**
