### PR TITLE
Add KeyDB

### PR DESCRIPTION
**Pull request by l0rem**
Hi, i would love to add [KeyDB](https://docs.keydb.dev/) to one-click-apps. 

It's pretty popular alternative (fork) to redis, at moment of writing it has 7.2k stars on [GH](https://github.com/Snapchat/KeyDB), 1M+ pulls on [DH](https://hub.docker.com/r/eqalpha/keydb) and some pretty big companies use it :)

Thanks!

### ☑️ Self Check before Merge

- [☑️] I have tested the template using the method described in README.md thoroughly
- [☑️] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [☑️] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [☑️] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [☑️] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by l0rem** [comment]
Maybe its a good idea to include prettier in the check-list, just to avoid a bit of confusion? 🙂

**Comment by githubsaturn** [comment]
Thanks!

**Comment by geoman2** [comment]
Hi, did you try DragonflyDB, is supposed to be up to x25 more performant than redis, but can't prove. What about KeyDB, first time heard about it

**Comment by l0rem** [comment]
@geoman2 i would suggest reading this thread - https://news.ycombinator.com/item?id=31796311

I have pretty much no experience with anything other than redis or keydb, so for now i am sticking with what works for me, but you should not be pressured into using what others are telling you to use. build your next thing with dragonfly and share your experiences, it would be interesting for me and many others :)

**Pull request merged**
