### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by kendofriendo**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [ ☑️ ] I have tested the template using the method described in README.md thoroughly
- [☑️ ] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [☑️ ] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [☑️ ] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [☑️ ] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by githubsaturn** [comment]
I don't see any official links to this repo. I'll revert the `isOfficial` flag to false. Please let me know if it's incorrect.

**Comment by kendofriendo** [comment]
The official link can be found in the [installation instructions](https://docs.invidious.io/installation/). 

> The Invidious docker image is only [available on Quay](https://quay.io/repository/invidious/invidious) because, unlike Docker Hub, [Quay is Free and Open Source Software](https://github.com/quay/quay/blob/master/LICENSE). This is reflected in the docker-compose.yml file used in this walk-through.

**Comment by githubsaturn** [comment]
Thanks! Updated.

**Pull request merged**
