### PR TITLE
Adding: LinkAce

### PR DESCRIPTION
**Pull request by wojtishek**
First of all, thank you for your contribution! 😄

Please note that this repo is mostly for popular apps with thousands of stars and tens of thousands of downloads. If you'd like to add a less popular app, you can always [create your own 3rd party repo](https://github.com/caprover/one-click-apps#build-your-own-one-click-app-repository) and add your app there.

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.
- [ ] I've executed the checks if necessary by running `npm ci && npm run validate_apps && npm run formatter` (If failling run the prettier: `npm run formatter-write`)
- [x] I will take responsibility addressing any issues that arises as a result of this PR (maintaining this app).

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by VictorioBerra** [comment]
@wojtishek Can we not append `-simple` to LinkAce tags? I am unable to use LinkAce 2.x because of this. There is no `2.x-simple`. Is there a reason we require this?

**Comment by VictorioBerra** [comment]
@wojtishek ARe we unable to use Beta? Should we create a new template for LinkAce-Beta?

**Comment by wojtishek** [comment]
@VictorioBerra better solution should be to create Linkace-simple and Linkace-advanced templates IMHO (https://www.linkace.org/docs/v1/setup/setup-with-docker/). I'm not Linkace developer, so not sure what type of deployment is beta version.

**Comment by wojtishek** [comment]
v2 is out, but changed image tags, I'll update one click app

@githubsaturn what will be best approach? leave current app, rename to v1 and create v2 app? depending upgrade guide there's one BC - `MAIL_DRIVER needs to be replaced with MAIL_MAILER, but the values stays the same. Example: MAIL_DRIVER=smtp becomes MAIL_MAILER=smtp`

**Comment by githubsaturn** [comment]
I recommend just changing the current one to v2. No need to keep v1.

**Comment by wojtishek** [comment]
#1199

**Pull request merged**
