### PR TITLE
Add Countly analytics as a one-click app

### PR DESCRIPTION
**Pull request by vohzd**
Thank you everyone! Here is a one-click app that is confirmed to work.

This app bootstraps itself (in the same way magento and wordpress do), so there's little need to add env vars.

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Documentation field contains a link to a page with proper explanations on environmental variables, volumes or the docker compose file.

### CODE REVIEW

**Comment by ronalddas** [comment]
@vohzd this isn't working. I think, mongodb has to be setup separately. This is the error  am getting 
```
ERROR	[db:read]	Error reading jobs {"name":"find","args":[{"status":0,"next":{"$lt":1589107956066},"name":{"$in":["api:clear","api:clearAutoTasks","api:clearTokens","api:ipcTest","api:ping","api:task","api:test","api:topEvents","api:userMerge","reports:send","push:clear","push:process","push:schedule","push:validate","server-stats:stats","assistant:generate","alerts:monitor"]}}]}
 MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017 {"name":"MongoServerSelectionError","reason":{"type":"Single","setName":null,"maxSetVersion":null,"maxElectionId":null,"servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":null,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":null}}
```

**Comment by githubsaturn** [comment]
If it had been tested originally and it's broken now, it's probably due to the usage of `latest`... That's why we avoid using this tag.... I'll change this to a fixed tag that was published at the time of this PR. `19.08.1`... @ronalddas  please retry with this tag `19.08.1` instead of `latest` and let me know if it works.

**Comment by ronalddas** [comment]
@githubsaturn Yeah its working with `19.08.1` . Although the deployment in caprover failed with a `502` status code, but the app was created and was able to setup admin account in countly

**Comment by vohzd** [comment]
Apologies! Yes when I tested with `latest` was working all OK - This is why from now on I'll be setting the explicit versions!

**Comment by eborges-git** [comment]
It doesn't work recent versions. Front end runs, but server doesn't receive data. Any idea on how to install Countly recent versions (23.03.2) without having to create multiple apps?

**Pull request merged**
