### PR TITLE
Bump Gitea/MySQL to latest versions

### PR DESCRIPTION
**Pull request by redwerkz**

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks for the PR. Have you tested the app with these new versions?

**Comment by redwerkz** [comment]
You got me, doesn't work with this MySQL version.
Sorry, didn't check this properly.

**Comment by redwerkz** [comment]
Didn't work properly because of misconfiguration of my caprover installation.
Now I tested this config again and it works. 
Sorry for the confusion.

**Comment by githubsaturn** [comment]
Thanks!

**Pull request merged**
