### PR TITLE
Add taiga.io

### PR DESCRIPTION
**Pull request by movabo**
Add a setup of taiga.io as per [docker-compose.yml](https://github.com/kaleidos-ventures/taiga-docker/blob/main/docker-compose.yml ) (for the deployment as [taiga.yml](https://github.com/caprover/one-click-apps/commit/9bdfe7f362043af44b269b6abe80354f64b61e1d#diff-5b1d9d70c42c4e23acb29f724335b9f3e5d719ccab6a17849e5f553ac62c256e)) and [docker-compose-inits.yml](https://github.com/kaleidos-ventures/taiga-docker/blob/main/docker-compose-inits.yml) (for the initial superuser setup as [taiga-superuser-setup.yml](https://github.com/caprover/one-click-apps/commit/9bdfe7f362043af44b269b6abe80354f64b61e1d#diff-5bd25b57dccc07822cb62c50070f9e3ab672937778ebe6db43dc3b5a12fd0435))

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by movabo** [comment]
I just saw, that there's still a problem with the events websockets.

**Comment by movabo** [comment]
Okay, it works now.

**Comment by movabo** [comment]
Okay, nevermind. The admin interface outputs an error in taiga-back when creating a new user:
```

2022-04-22T11:53:00.926847423Z ERROR:2022-04-22 11:52:58,676: Internal Server Error: /admin/users/user/add/
2022-04-22T11:53:00.928056389Z Traceback (most recent call last):
2022-04-22T11:53:00.928065054Z   File "/opt/venv/lib/python3.7/site-packages/kombu/utils/functional.py", line 30, in __call__
2022-04-22T11:53:00.928068441Z     return self.__value__
2022-04-22T11:53:00.928072017Z AttributeError: 'ChannelPromise' object has no attribute '__value__'
2022-04-22T11:53:00.928075584Z 
2022-04-22T11:53:00.928078930Z During handling of the above exception, another exception occurred:
2022-04-22T11:53:00.928082467Z 
2022-04-22T11:53:00.928090612Z Traceback (most recent call last):
2022-04-22T11:53:00.928095521Z   File "/opt/venv/lib/python3.7/site-packages/amqp/transport.py", line 173, in _connect
2022-04-22T11:53:00.928099328Z     host, port, family, socket.SOCK_STREAM, SOL_TCP)
2022-04-22T11:53:00.928103015Z   File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
2022-04-22T11:53:00.928107103Z     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2022-04-22T11:53:00.928110469Z socket.gaierror: [Errno -2] Name or service not known
2022-04-22T11:53:00.928113655Z 
2022-04-22T11:53:00.928116911Z During handling of the above exception, another exception occurred:
2022-04-22T11:53:00.928120167Z 
2022-04-22T11:53:00.928123974Z Traceback (most recent call last):
2022-04-22T11:53:00.928127761Z   File "/opt/venv/lib/python3.7/site-packages/kombu/connection.py", line 447, in _reraise_as_library_errors
2022-04-22T11:53:00.928131317Z     yield
2022-04-22T11:53:00.928134383Z   File "/opt/venv/lib/python3.7/site-packages/kombu/connection.py", line 438, in _ensure_connection
2022-04-22T11:53:00.928138240Z     callback, timeout=timeout
2022-04-22T11:53:00.928142218Z   File "/opt/venv/lib/python3.7/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
2022-04-22T11:53:00.928146035Z     return fun(*args, **kwargs)
2022-04-22T11:53:00.928149361Z   File "/opt/venv/lib/python3.7/site-packages/kombu/connection.py", line 878, in _connection_factory
2022-04-22T11:53:00.928153940Z     self._connection = self._establish_connection()
2022-04-22T11:53:00.928157647Z   File "/opt/venv/lib/python3.7/site-packages/kombu/connection.py", line 813, in _establish_connection
2022-04-22T11:53:00.928160903Z     conn = self.transport.establish_connection()
2022-04-22T11:53:00.928164379Z   File "/opt/venv/lib/python3.7/site-packages/kombu/transport/pyamqp.py", line 201, in establish_connection
2022-04-22T11:53:00.928180118Z     conn.connect()
2022-04-22T11:53:00.928183564Z   File "/opt/venv/lib/python3.7/site-packages/amqp/connection.py", line 323, in connect
2022-04-22T11:53:00.928186570Z     self.transport.connect()
2022-04-22T11:53:00.928189445Z   File "/opt/venv/lib/python3.7/site-packages/amqp/transport.py", line 113, in connect
2022-04-22T11:53:00.928192782Z     self._connect(self.host, self.port, self.connect_timeout)
2022-04-22T11:53:00.928196178Z   File "/opt/venv/lib/python3.7/site-packages/amqp/transport.py", line 184, in _connect
2022-04-22T11:53:00.928202079Z     "failed to resolve broker hostname"))
2022-04-22T11:53:00.928204534Z OSError: failed to resolve broker hostname
2022-04-22T11:53:00.928206768Z 
2022-04-22T11:53:00.928208892Z The above exception was the direct cause of the following exception:
2022-04-22T11:53:00.928211156Z 
2022-04-22T11:53:00.928214372Z Traceback (most recent call last):
2022-04-22T11:53:00.928217338Z   File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
2022-04-22T11:53:00.928220544Z     response = get_response(request)
2022-04-22T11:53:00.928223369Z   File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
2022-04-22T11:53:00.928226285Z     response = self.process_exception_by_middleware(e, request)
2022-04-22T11:53:00.928229130Z   File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
2022-04-22T11:53:00.928232135Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2022-04-22T11:53:00.928235140Z   File "/opt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
2022-04-22T11:53:00.928238697Z     return self.admin_site.admin_view(view)(*args, **kwargs)
2022-04-22T11:53:00.928241532Z   File "/opt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
2022-04-22T11:53:00.928244648Z     response = view_func(request, *args, **kwargs)
2022-04-22T11:53:00.928247583Z   File "/opt/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
2022-04-22T11:53:00.928250649Z     response = view_func(request, *args, **kwargs)
2022-04-22T11:53:00.928253465Z   File "/opt/venv/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
2022-04-22T11:53:00.928256600Z     return view(request, *args, **kwargs)
2022-04-22T11:53:00.928259406Z   File "/opt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
2022-04-22T11:53:00.928262501Z     return bound_method(*args, **kwargs)
2022-04-22T11:53:00.928265507Z   File "/opt/venv/lib/python3.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
2022-04-22T11:53:00.928268843Z     return view(request, *args, **kwargs)
2022-04-22T11:53:00.928289231Z   File "/opt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
2022-04-22T11:53:00.928292256Z     return bound_method(*args, **kwargs)
2022-04-22T11:53:00.928294490Z   File "/opt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
2022-04-22T11:53:00.928297556Z     response = view_func(request, *args, **kwargs)
2022-04-22T11:53:00.928300542Z   File "/opt/venv/lib/python3.7/site-packages/django/contrib/auth/admin.py", line 99, in add_view
2022-04-22T11:53:00.928303608Z     return self._add_view(request, form_url, extra_context)
2022-04-22T11:53:00.928306904Z   File "/opt/venv/lib/python3.7/site-packages/django/db/transaction.py", line 284, in __exit__
2022-04-22T11:53:00.928310120Z     connection.set_autocommit(True)
2022-04-22T11:53:00.928324517Z   File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 410, in set_autocommit
2022-04-22T11:53:00.928327973Z     self.run_and_clear_commit_hooks()
2022-04-22T11:53:00.928330949Z   File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 636, in run_and_clear_commit_hooks
2022-04-22T11:53:00.928334115Z     func()
2022-04-22T11:53:00.928337601Z   File "/taiga-back/taiga/timeline/signals.py", line 36, in <lambda>
2022-04-22T11:53:00.928341427Z     refresh_totals=refresh_totals))
2022-04-22T11:53:00.928343772Z   File "/opt/venv/lib/python3.7/site-packages/celery/app/task.py", line 425, in delay
2022-04-22T11:53:00.928346206Z     return self.apply_async(args, kwargs)
2022-04-22T11:53:00.928348551Z   File "/opt/venv/lib/python3.7/site-packages/celery/app/task.py", line 579, in apply_async
2022-04-22T11:53:00.928350955Z     **options
2022-04-22T11:53:00.928353180Z   File "/opt/venv/lib/python3.7/site-packages/celery/app/base.py", line 788, in send_task
2022-04-22T11:53:00.928355584Z     amqp.send_task_message(P, name, message, **options)
2022-04-22T11:53:00.928357868Z   File "/opt/venv/lib/python3.7/site-packages/celery/app/amqp.py", line 519, in send_task_message
2022-04-22T11:53:00.928360283Z     **properties
2022-04-22T11:53:00.928362497Z   File "/opt/venv/lib/python3.7/site-packages/kombu/messaging.py", line 180, in publish
2022-04-22T11:53:00.928364871Z     exchange_name, declare, timeout
2022-04-22T11:53:00.928367096Z   File "/opt/venv/lib/python3.7/site-packages/kombu/connection.py", line 524, in _ensured
2022-04-22T11:53:00.928369500Z     return fun(*args, **kwargs)
2022-04-22T11:53:00.928371764Z   File "/opt/venv/lib/python3.7/site-packages/kombu/messaging.py", line 186, in _publish
2022-04-22T11:53:00.928374139Z     channel = self.channel
2022-04-22T11:53:00.928376353Z   File "/opt/venv/lib/python3.7/site-packages/kombu/messaging.py", line 209, in _get_channel
2022-04-22T11:53:00.928378707Z     channel = self._channel = channel()
2022-04-22T11:53:00.928384719Z   File "/opt/venv/lib/python3.7/site-packages/kombu/utils/functional.py", line 32, in __call__
2022-04-22T11:53:00.928387183Z     value = self.__value__ = self.__contract__()
2022-04-22T11:53:00.928389468Z   File "/opt/venv/lib/python3.7/site-packages/kombu/messaging.py", line 225, in <lambda>
2022-04-22T11:53:00.928391952Z     channel = ChannelPromise(lambda: connection.default_channel)
2022-04-22T11:53:00.928394257Z   File "/opt/venv/lib/python3.7/site-packages/kombu/connection.py", line 896, in default_channel
2022-04-22T11:53:00.928396670Z     self._ensure_connection(**conn_opts)
2022-04-22T11:53:00.928400407Z   File "/opt/venv/lib/python3.7/site-packages/kombu/connection.py", line 438, in _ensure_connection
2022-04-22T11:53:00.928403753Z     callback, timeout=timeout
2022-04-22T11:53:00.928408102Z   File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
2022-04-22T11:53:00.928411298Z     self.gen.throw(type, value, traceback)
2022-04-22T11:53:00.928414363Z   File "/opt/venv/lib/python3.7/site-packages/kombu/connection.py", line 451, in _reraise_as_library_errors
2022-04-22T11:53:00.928417669Z     raise ConnectionError(str(exc)) from exc
2022-04-22T11:53:00.928419954Z kombu.exceptions.OperationalError: failed to resolve broker hostname
```

**Comment by movabo** [comment]
Okay, that's fixed now as well. On my instance it seems to be running fine now! :)

**Comment by movabo** [comment]
I updated the description.

**Comment by githubsaturn** [comment]
Please run `npm run formatter-write`

**Comment by githubsaturn** [comment]
https://github.com/caprover/one-click-apps/issues/705

**Pull request closed without merging**
