### PR TITLE
FusionAuth

### PR DESCRIPTION
**Pull request by r-t-k**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Documentation field contains a link to a page with proper explanations on environmental variables, volumes or the docker compose file.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Hi @r-t-k 

Thanks for PR. What's the minimum spec for running this? I have a 2GB vps and this fails to start. It may be a resource issue?

**Comment by r-t-k** [comment]
That’s a good question. They have this page: https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements but that isn’t helpful for hardware requirements.  I’d think that 2-4gb would be enough depending on what else is eating up resources. What do your logs say?

**Comment by githubsaturn** [comment]
It appears it's the elastic search that causes the problem on 2GB... It keeps restarting... Having said that, it runs fine on 4GB RAM.

Can you please add a note to `instructions.start` highlighting the minimum RAM requirement?

**Comment by r-t-k** [comment]
Absolutely, thank you for helping discover this issue

**Pull request merged**
