### PR TITLE
Fix docker hub ref for firefly

### PR DESCRIPTION
**Pull request by Church13**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

The official docker hub image for Firefly III has moved -- this PR fixes the ref.

### CODE REVIEW

**Comment by Church13** [comment]
As per https://hub.docker.com/r/jc5x/firefly-iii -- the old jc5x/firefly-iii hub image has been deprecated, and Firefly III is moving to fireflyiii/core (https://hub.docker.com/r/fireflyiii/core).

**Comment by githubsaturn** [comment]
Have you tested this PR? Looks like the default tag is no longer available under `fireflyiii/core`.

**Comment by Church13** [comment]
> Have you tested this PR? Looks like the default tag is no longer available under `fireflyiii/core`.

I did test it, but manually specified the tag on my install -- corrected to reflect a recent, available tag in the fireflyiii/core docker hub. Good catch.

**Comment by githubsaturn** [comment]
Perfect, thanks!

**Pull request merged**
