### PR TITLE
✨ Added Duplicati & removed port mapping in lychee 🔧

### PR DESCRIPTION
**Pull request by kgnfth**
### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

Fully Tested

image

### CODE REVIEW

**Comment by githubsaturn** [comment]
This is really nice! Thanks!

**Comment by githubsaturn** [comment]
> I tried adding /var/lib/docker/volumes as a persistent source but caprover would not accept it.

What do you mean CapRover wouldn't accept it? You can map any directory of the host to any directory in the container.

**Comment by coffseducation** [comment]
I could not add more than one
/source /directory
Caprover threw an error message.

I left the source at / to access all directories.
Duplicati give a guid and puid as 1000 in settings.
I changed this to root  "0" and can now access the docker volumes, so in the end did not need multiple sources configured.

nb. Should the Duplicati One Click app uid settings be changed to "0" - or at least have a note about this in setup?
Reason: Noobies like myself will choose a One Click app, and go with defaults that have data in Docker volumes rather than in user directories. 0 would make more sense and save the new user from spending days finding the answer.

Thanks.

**Comment by githubsaturn** [comment]
> I could not add more than one
/source /directory
Caprover threw an error message.

What was the error message?

Log in to https://captain.server.demo.caprover.com with password of `captain42` and check out `test-directory-mapping`

image

**Comment by coffseducation** [comment]
image
"Something bad happened"

Two sources probably confuses Duplicati.
Is there somewhere I can find logs?

**Comment by kgnfth** [comment]
> image "Something bad happened"
> 
> Two sources probably confuses Duplicati. Is there somewhere I can find logs?

That's because `/var/lib/docker/` is already in the root folder `/`
Just remove the source `/var/lib/docker/`

**Comment by githubsaturn** [comment]
@coffseducation - You can't map two different directories to the same directory in the container. Mappings should be 1:1

**Pull request merged**
