### PR TITLE
Appsmith with database

### PR DESCRIPTION
**Pull request by aqidd**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks for the PR! 

Just one question: the Docker Compose file in their [official guide](https://docs.appsmith.com/setup/docker) has a volume at `/appsmith-stacks` - was this removed on purpose?

**Comment by aqidd** [comment]
Ah you're right. Upon further checks, this volume is useful when you do a db dump. Will update the definition with volume

**Comment by aaron5670** [comment]
Looks great! 👍

**Comment by githubsaturn** [comment]
Thank you!

**Pull request merged**
