### PR TITLE
added memos notes management

### PR DESCRIPTION
**Pull request by x4m3**
Added memos notes management https://usememos.com

Tested on my server, works like a charm!

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by githubsaturn** [comment]
Looks like the build is failed, probably just need to run `npm run formatter-write`

**Comment by x4m3** [comment]
Ran the script, the file got updated!

When I added my one-click-app, i followed the instructions at the bottom of the readme, should I add the formatter-write command inside the readme?

Also, I copied/pasted from the example at the top of the readme, which is the reason why the build failed, should I fix it as well?

**Comment by githubsaturn** [comment]
Yes, please feel free to update the docs!

**Comment by x4m3** [comment]
Will do! Thank you for your work on caprover, its awesome! You're making my life so much easier!

**Pull request merged**
