### PR TITLE
passbolt

### PR DESCRIPTION
**Pull request by belcboo**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.
- [x] Documentation field contains a link to a page with proper explanations on environmental variables, volumes or the docker compose file.

This app uses the official image and documentation from Passbolt. Is another alternative to password manager for users and teams.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Have you fully tested this? Some of the keys set here are ignored by CapRover. If this is tested and working, it means that those keys are not important at all. For example `command` is not used by CapRover.

**Comment by belcboo** [comment]
> Have you fully tested this? Some of the keys set here are ignored by CapRover. If this is tested and working, it means that those keys are not important at all. For example `command` is not used by CapRover.

Yes, I’m currently using it in a project with some friends and we haven’t had any issue. If you want me to remove those keys I can, just let me know what other key is not used by Caprover. 

Thanks.

**Comment by githubsaturn** [comment]
The info is in README:
image

In your case,  you can remove `tty` `tmpfs` and `command`

**Comment by githubsaturn** [comment]
Great, thanks! Once it's available on the official repo, I suggest test it again to make sure that it works as expected!

**Pull request merged**
