### PR TITLE
feat: add keila

### PR DESCRIPTION
**Pull request by ronaldloyko**
This pull request adds [Keila](https://www.keila.io).

## Checks

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by uhlhosting** [comment]
This does not works on https with caprover's default mechanism. Do someone verifies apps before allowing them in?

**Comment by githubsaturn** [comment]
The author is supposed to test them (the first checkbox above). And it looks like it was tested.

What's the issue?

**Comment by ronaldloyko** [comment]
I'm still using it in production, so it was definitely tested by me.

That "verification failed" error happened to me as well in various apps. I did the workaround described in the documentation and problem solved.

**Pull request merged**
