### PR TITLE
Add ohmyforms

### PR DESCRIPTION
**Pull request by NeoTheThird**
This adds a one-click config for [ohmyforms](https://ohmyform.com/) using scalable microservices for redis, mongodb, mailhog, and separate containers for the ui and api.

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by githubsaturn** [comment]
FYI - looks like people have issues with this one click app: https://github.com/caprover/caprover/issues/894

**Comment by NeoTheThird** [comment]
Sorry to hear that. I'm pretty swamped with work right now, but i'll try to take a look soon. The OhMyForm install i set up with this config is still running fine on my caprover.

**Comment by aqidd** [comment]
I have the same issues as well. To give more context, the error happens when calling `/graphql` endpoint. Instead of getting a response, error happened with status `ERR_CERT_AUTHORITY_INVALID`

**Comment by jumus-jumbuck** [comment]
From what I can see, the deployment window of the api says it cannot connect to database, but everything is running, then I see this https://github.com/ohmyform/api/blob/master/doc/environment.md which shows sqlite or postegres no mongo, I will have a play and try and configure the one click to be postgres, if I am successful I will submit it

**Comment by timconsidine** [comment]
Trying to install ohmyform as one-click on self-hosted caprover
Successful build and deploy
Login page displays with error : `There is an error with your API connection: Unexpected token < in JSON at position 0`
Any suggestions how to resolve ?

**Comment by githubsaturn** [comment]
@timconsidine  - looks like OhMyForm is not actively being maintained. I changed some of the parameters to match to the latest example. But not sure if it fixes the issue.

Give it a show again and let me know if it works or not. If it's still broken, I'll remove it from the list to avoid confusion.

**Comment by githubber** [comment]
It's still not working. Install seems to go fine. Can not login. Shame.

**Comment by githubsaturn** [comment]
@githubber  - I suggest opening an issue with them. Post installation issues aren't CapRover bugs, they are application specific bugs. Here is their github page: https://github.com/ohmyform/ohmyform

**Comment by githubber** [comment]
Re-open this. Using Caprover, latest. With OhMyForms. Admin login, regular login, both saying username / password are invalid. Still a shame. I double checked the various env variables and its all as it should be.
There is an extra notice though: 2022-02-24T10:47:37.132751429Z {"level":50,"time":1645699657132,"pid":34,"hostname":"799e63f45d90","context":"MongooseModule","trace":"","msg":"Unable to connect to the database. Retrying (6)..."}

**Comment by githubsaturn** [comment]
Updated based on their official dockerfile. Please try again. Let me know if it still fails.

**Comment by githubber** [comment]
> Updated based on their official dockerfile. Please try again. Let me know if it still fails.

I've tried but it fails at "Deploying forms (might take up to a minute)" with an error message at the bottom of the screen reading, "Failed: Error: Request failed with status code 500".  Does the image reference in the updated ohmyforms yml need to be something like "ohmyform/ohmyform/releases/tag/0.9.9"?

**Comment by githubber** [comment]
Nope, still a db connection error. I would LLLOOOOVVEEE to get this thing working... but I just dont know. I wish I could help somehow. Maybe it's better to remove this app from the list. 

vps@box:~$ docker service logs srv-captain--form --since 60m --follow
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/services/srv-captain--form?insert Defaults=false": dial unix /var/run/docker.sock: connect: permission denied
vps@box:~$ ^C
vps@box:~$ sudo docker service logs srv-captain--form --since 60m --follow
srv-captain--form.1.oo28x4zuiut9@box.example.com    | yarn run v1.22.5
srv-captain--form.1.oo28x4zuiut9@box.example.com    | $ cross-env NODE_ENV=production node dist/main
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618697,"pid":34,"hostname":"cefc1409fac3","context":"NestFactory","msg":"Starting Nest application..."}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618818,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"LoggerModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618819,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"MongooseModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618819,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"MailerModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618822,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"HttpModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618824,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"ConfigHostModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618826,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"LoggerCoreModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618826,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"ServeStaticModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618827,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"ConsoleModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618827,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"ConfigModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618828,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"ConfigModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":40,"time":1645875618830,"pid":34,"hostname":"cefc1409fac3","msg":"without redis graphql subscriptions will be unreliable in load balanced environments"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618856,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"MailerCoreModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618857,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"JwtModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618857,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"GraphQLSchemaBuilderModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":30,"time":1645875618858,"pid":34,"hostname":"cefc1409fac3","context":"InstanceLoader","msg":"GraphQLModule dependencies initialized"}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":50,"time":1645875648873,"pid":34,"hostname":"cefc1409fac3","context":"MongooseModule","trace":"","msg":"Unable to                  connect to the database. Retrying (1)..."}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":50,"time":1645875681881,"pid":34,"hostname":"cefc1409fac3","context":"MongooseModule","trace":"","msg":"Unable to                  connect to the database. Retrying (2)..."}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":50,"time":1645875714889,"pid":34,"hostname":"cefc1409fac3","context":"MongooseModule","trace":"","msg":"Unable to                  connect to the database. Retrying (3)..."}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":50,"time":1645875747897,"pid":34,"hostname":"cefc1409fac3","context":"MongooseModule","trace":"","msg":"Unable to                  connect to the database. Retrying (4)..."}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":50,"time":1645875780905,"pid":34,"hostname":"cefc1409fac3","context":"MongooseModule","trace":"","msg":"Unable to connect to the database. Retrying (5)..."}
srv-captain--form.1.oo28x4zuiut9@box.example.com    | {"level":50,"time":1645875813913,"pid":34,"hostname":"cefc1409fac3","context":"MongooseModule","trace":"","msg":"Unable to connect to the database. Retrying (6)..."}

**Comment by githubsaturn** [comment]
I removed the app from the official repo until someone fixes and tests it.

**Comment by githubsaturn** [comment]
Okay found the issue. It's because their docker compose examples only work on the `latest` tag as they have introduced breaking changes. Will change the docker-compose to 0.9.9 to ensure that it works.

**Comment by githubsaturn** [comment]
Their version only has the name, no tags. Without tag, docker default to `latest` which is not a "released" version, it's the development branch. Their latest release version is 0.9.9 according to their github releases.

**Comment by githubber** [comment]
<p><a href="https://giphy.com/gifs/awesome-you-did-it-4QEGzwV57p27EbVHXG">YOU DID IT!!!</a></p>
IT IS WORKING!!!

I added `SIGNUP_DISABLED` = true, and even though the "Create Account" link is visible, there is a red crossed-out circle over it when I try to click on it... so now no one else can register. Perfect. (Read both https://ohmyform.com/docs/env/ and https://github.com/ohmyform/api/blob/master/doc/environment.md to get the right terms for the env variables.

**Comment by githubber** [comment]
**Thank you so much** for your patience and endurance in helping get this on Caprover.

**Comment by githubber** [comment]
Well, I can login, but any form I create is not saved. Did it need persistent storage or something?

**Comment by githubber** [comment]
Also, I recall there was a "form-api" image installed last time. The mongodb is present this time, but no form-api. Could that be why the forms aren't being saved?

**Comment by githubber** [comment]
And once logged in, there is this in the bottom left: `Version: 0.9.8`

**Comment by githubber** [comment]
One more update, then I gotta hit the hay: If I log out, and log back in, then the forms are now visible.

**Comment by githubsaturn** [comment]
Issues like this are application issues and better be suited for the application maintainer. Caprover is just the installation tool.

**Pull request merged**
