### PR TITLE
add filestash

### PR DESCRIPTION
**Pull request by prabirshrestha**
### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version. 
updated to use `b7b45f2` https://hub.docker.com/r/machines/filestash/tags
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.
- [x] Documentation field contains a link to a page with proper explanations on environmental variables, volumes or the docker compose file.

//cc @mickael-kerjean

### CODE REVIEW

**Comment by githubsaturn** [comment]
We shouldn't default to `latest` tag. This will mean that if the developer of the image makes changes to the API, such as required env vars and etc, the image will break.

If the developer doesn't provide specific tags, let's use a sha256 tag for that image.

**Comment by prabirshrestha** [comment]
Updated the version to use `b7b45f2`

**Comment by githubsaturn** [comment]
Great, thanks!

**Comment by paluigi** [comment]
Hello, I have the following issue with Filestash 1-click app.
It deploys successfully, but then it has issues in running. In the logs I get the following message:

`2023-04-26T11:37:26.825147595Z exec /app/filestash: exec format error`

I tried to change the image tag from the default one to a more recent one, but the issue is the same.
Any hint about how to fix this, or any other info I can provide to help debug?
Thanks

**Comment by paluigi** [comment]
Ok, I see. I was actually deploying on a ARM CPU, hence the error. Thanks for clarifying!

**Pull request merged**
