### PR TITLE
Tidy instructions spelling & spacing

### PR DESCRIPTION
**Pull request by edwardch**
Updated spacing, layout, spelling, etc in display names and start/end instructions

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by edwardch** [comment]
>  Checking formatting...
> public/v4/apps/collabora-online.yml
> public/v4/apps/squidex.yml
> public/v4/apps/the-lounge.yml
> Code style issues found in the above file(s). Forgot to run Prettier?

Seems I did something wrong with running my Prettier (Windows). 

Will look again

**Comment by githubsaturn** [comment]
Thanks for the fixes! Just be careful, this is going to cause conflicts very soon if we make any changes, so I suggest you fix the formatter and update the PR soon.

**Comment by edwardch** [comment]
The validate_apps didn't pick up errors on macOS either, and all I can think of is that my node/npm versions are different to the one in setup-node build action. I had to find these the good old-fashioned way - by eye.

I'm glad the check is in place!

**Comment by githubsaturn** [comment]
Thanks!

Was it automated in some way? If so, feel free to move the logic to the repo as a github action so that we won't break these again.

**Comment by edwardch** [comment]
Sure thing!

Unfortunately nothing automated from my side. I'll try to explore some ideas though!

Thanks for accepting the PR.

**Pull request merged**
