### PR TITLE
add neo4j

### PR DESCRIPTION
**Pull request by aksanoble**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by Ak4zh** [comment]
You may have to run prettier to fix formatting.

`prettier --write './public/**/*.(json|yml)'`

**Comment by githubsaturn** [comment]
Thanks!

**Comment by fishnux** [comment]
I have a question regarding the location of the volume of Neo4j data. This is what Neo4j says:
```
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
  ```
 But the Docker volume is mounted at /data instead of  /var/lib/neo4j/data - is this ok?

**Comment by aksanoble** [comment]
@fishnux Also see the paths for the volumes attached to neo4j docker container as documented here: https://neo4j.com/developer/docker-run-neo4j/

**Pull request merged**
