### PR TITLE
feat: add redash

### PR DESCRIPTION
**Pull request by ronaldloyko**
This pull request adds the one-click-application for [Redash](https://redash.io).

## Checks

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by uhlhosting** [comment]
@ronaldloyko the redash app does not deploy anymore with default settings on caprover, can you please update it to work?

**Comment by ronaldloyko** [comment]
> @ronaldloyko the redash app does not deploy anymore with default settings on caprover, can you please update it to work?

@uhlhosting I have just deployed a fresh instance and it's working.

**Comment by ronaldloyko** [comment]
Hi @ercangurevin 

Were you able to solve the problem in the meantime?

Otherwise, I will try to help you as much as possible.
For this, I would need more context and information about the error (which data sources are affected, which version, etc.).

**Comment by ercangurevin** [comment]
> Hi @ercangurevin
> 
> Were you able to solve the problem in the meantime?
> 
> Otherwise, I will try to help you as much as possible. For this, I would need more context and information about the error (which data sources are affected, which version, etc.).

I couldn't solve the problem yet.

I deploy redash via one-clik-app and did not change any version. 
Application version 10.1.0.b50633
Queue version 7.0-alpine
DB version 15.0-alpine


And tried to add mongo, postgresql, sql server datasources to create a dashboard but it gives the error mentioned earlier.

Have you be able to deploy redash and connect to any datasource successfully ? @ronaldloyko

**Pull request merged**
