### PR TITLE
add FreshRSS

### PR DESCRIPTION
**Pull request by lcx**
Add FreshRSS from official docker image

> FreshRSS is a self-hosted RSS and Atom feed aggregator.
> It is lightweight, easy to work with, powerful, and customizable.

Since I know we are all lazy with backups, I have included an automated PSQL Dump to create backups. Unfortunately this docker image only has a "latest" tag.

First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Backup app is an interesting idea. Wouldn't it be better if it's a standalone one click app? Users will be able to use it for all apps that use Postgres under the hood, not just FreshRSS.

**Comment by christopher-kapic** [comment]
Postgres backups would be a great feature for Caprover in general. I have a [half-baked repo](https://github.com/christopher-kapic/pg_capup), but an official feature would be nice.

**Comment by lcx** [comment]
ok, removed the backup from freshrss. The issue is that people like me are lazy, they will postpone backups for some other day and at some point forget completely that's why I prefer to add the backup in the one click to prevent people forgetting. But maybe something that can be used for all containers would make more sense.

**Comment by githubsaturn** [comment]
Thanks!

**Pull request merged**
