### PR TITLE
[WIP] Add Penpot

### PR DESCRIPTION
**Pull request by sardaukar**
First of all, thank you for your contribution! 😄

### ☑️ Self Check before Merge

- [x] I have tested the template using the method described in README.md thoroughly
- [x] I have ensured that I put as much default values as possible (except passwords) to ensure minimum effort required for end users to get started.
- [x] I have ensured that I am not using the "latest" tag as this tag is dynamically changing and might break the one-click app. Use a fixed version.
- [x] I have made sure that instructions.start and instructions.end are clear and self-explanatory.
- [x] Icon is added as a png file to the logos directory.

Just need a little help with this template for Penpot (https://github.com/penpot/penpot)

Not sure what I'm doing wrong, but I get 

image

when deploying. The original docker-compose is [here](https://raw.githubusercontent.com/penpot/penpot/develop/docker/images/docker-compose.yaml)

Please help. Thanks!

### CODE REVIEW

**Comment by githubsaturn** [comment]
Just replace underscores with hyphens in your volumes:
```
cap_appname_db_data => cap_appname-db-data
cap_appname_assets_data => cap_appname-assets-data
```

**Comment by sardaukar** [comment]
Getting 

```
2021-02-07T17:10:16.229453788Z 2021/02/07 17:10:16 [emerg] 1#1: host not found in upstream "penpot-backend" in /etc/nginx/nginx.conf:72
2021-02-07T17:10:16.229512151Z nginx: [emerg] host not found in upstream "penpot-backend" in /etc/nginx/nginx.conf:72
```

**Comment by githubsaturn** [comment]
@sardaukar - all CapRover services are prefixed with `srv-captain--`. Probably there is an env var or something that allow you to specify the backend URL to be `srv-captain--penpot-backend` instead of `penpot-backend`

**Comment by githubsaturn** [comment]
It's not the only place that you need to update, for example this is wrong:
```
PENPOT_REDIS_URI: redis://$$cap_appname-redis/0
```
It should be
```
PENPOT_REDIS_URI: redis://srv-captain--$$cap_appname-redis/0
```

**Comment by githubsaturn** [comment]
Looks like these are hardcoded: https://github.com/penpot/penpot/blob/develop/docker/images/files/nginx.conf#L71-L87

I don't think it's easily possible to bring this as a one click app.

**Comment by sardaukar** [comment]
@githubsaturn can't a custom nginx config be used?

**Comment by githubsaturn** [comment]
This nginx config is inside the penpot-frontend image:
https://github.com/penpot/penpot/blob/develop/docker/images/Dockerfile.frontend#L4-L6

It has to be changed to be customizable by penpot folks. There is nothing that you can do on CapRover side to change this.

**Comment by sardaukar** [comment]
OK thanks for all your help!

**Comment by kgnfth** [comment]
Maybe i can help you pls reopen this issue
i think we can modify penpotapp/frontend using dockerfileLines

**Comment by kgnfth** [comment]
@sardaukar i have made it work

**Comment by sardaukar** [comment]
@kgnfth cool, reopened

**Comment by kgnfth** [comment]
> @kgnfth cool, reopened

Thx but i see that the backend is not working 
i am getting `Execution error (ExceptionInfo) at app.common.exceptions/error (exceptions.cljc:31).`
not sure what that means

**Comment by sardaukar** [comment]
Can you share your tweaks? So I can reproduce locally and follow up with Penpot's issues to try and find it

**Comment by githubsaturn** [comment]
Folks - I strongly suggest creating a PR and fixing it on the penpot-front side to be configurable. Patching dockerfile can work, but it'd be fragile for future releases of penpot.

**Comment by kgnfth** [comment]
@sardaukar 

```yaml
captainVersion: 4

services:
    $$cap_appname-db:
        image: 'postgres:13'
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_INITDB_ARGS: --data-checksums
            POSTGRES_DB: penpot
            POSTGRES_USER: penpot
            POSTGRES_PASSWORD: penpot
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-redis:
        image: 'redis:6'
        restart: always
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-exporter:
        image: 'penpotapp/exporter:1.1.0-alpha'
        restart: always
        environment:
            PENPOT_PUBLIC_URI: 'http://penpot-frontend'
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-backend:
        image: 'penpotapp/backend:1.1.0-alpha'
        volumes:
            - $$cap_appname-assets-data:/opt/data
        environment:
            PENPOT_PUBLIC_URI: $$cap_public_uri
            PENPOT_TELEMETRY_ENABLED: false # no one wants this enabled anyway
            PENPOT_SMTP_DEFAULT_FROM: $$cap_smtp_from
            PENPOT_SMTP_DEFAULT_REPLY_TO: $$cap_smtp_reply_to
            PENPOT_SMTP_HOST: $$cap_smtp_host
            PENPOT_SMTP_PORT: $$cap_smtp_port
            PENPOT_SMTP_USERNAME: $$cap_smtp_username
            PENPOT_SMTP_PASSWORD: $$cap_smtp_password
            PENPOT_SMTP_TLS: $$cap_smtp_tls
            PENPOT_SMTP_SSL: $$cap_smtp_ssl

            PENPOT_DATABASE_URI: postgresql://$$cap_appname-db/penpot
            PENPOT_DATABASE_USERNAME: penpot
            PENPOT_DATABASE_PASSWORD: penpot
            PENPOT_REDIS_URI: redis://$$cap_appname-redis/0
            PENPOT_STORAGE_BACKEND: fs
            PENPOT_STORAGE_FS_DIRECTORY: /opt/data/assets
            PENPOT_SMTP_ENABLED: true
        depends_on:
            - $$cap_appname-db
            - $$cap_appname-redis
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-frontend:
        volumes:
            - $$cap_appname-assets-data:/opt/data
        caproverExtra:
            dockerfileLines:
                - FROM penpotapp/frontend:1.1.0-alpha
                - RUN sed -i 's/penpot-backend/srv-captain--$$cap_appname-backend/g' /etc/nginx/nginx.conf
                - RUN sed -i 's/penpot-exporter/srv-captain--$$cap_appname-exporter/g' /etc/nginx/nginx.conf
        depends_on:
            - $$cap_appname-backend
            - $$cap_appname-exporter

caproverOneClickApp:
    variables:
        - id: $$cap_public_uri
          label: Public URI
          defaultValue: https://penpot
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_from
          label: STMP from address
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_reply_to
          label: STMP reply address
          defaultValue: no-reply@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_host
          label: STMP host
          defaultValue: smtp.example.com
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_port
          label: STMP port
          defaultValue: 587
          validRegex: /^^((6553[0-5])|(655[0-2][0-9])|(65[0-4][0-9]{2})|(6[0-4][0-9]{3})|([1-5][0-9]{4})|([0-5]{0,5})|([0-9]{1,4}))$$/
        - id: $$cap_smtp_username
          label: STMP username
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_password
          label: STMP password
          defaultValue:
          validRegex: /.{1,}/
        - id: $$cap_smtp_tls
          label: STMP TLS support
          defaultValue: true
          validRegex: /^(true|false)$/
        - id: $$cap_smtp_ssl
          label: STMP SSL support
          defaultValue: false
          validRegex: /^(true|false)$/
    instructions:
        start: >-
            The open-source solution for design and prototyping.
        end: >
            Penpot is deployed and available as $$cap_appname-frontend. IMPORTANT: It will take up to 2 minutes for Penpot to be ready. Before that, you might see a 502 error page.
    displayName: Penpot
    isOfficial: true
    description: The open-source solution for design and prototyping.
    documentation: Official docs are [here](https://github.com/penpot/penpot/tree/develop/docs)
```

@githubsaturn you are right lets do it

**Comment by sardaukar** [comment]
@kgnfth thanks, I'll try to figure oit what's wrong with the app. @githubsaturn you're right, this is just a workaround. Penpot is still in alpha so I hope I can propose a change soon.

**Comment by kgnfth** [comment]
i opened an issue https://github.com/penpot/penpot/issues/596
i am soo bad at explaining 🤦‍♂️

**Comment by sardaukar** [comment]
@kgnfth do we have an existing CapRover app that does this? (meaning, that the nginx upstream URIs are configurable) maybe by showing on the Penpot issue how it _could_ be done, they'll understand it better

**Comment by sardaukar** [comment]
There's no way of telling why it's crashing, since the crash log goes into `/tmp` and that's an in-memory FS that gets wiped when the container stops...

**Comment by kgnfth** [comment]
@sardaukar Maybe the nginx reverse proxy app ? docker code is available here https://github.com/caprover/nginx-reverse-proxy
and template here https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/nginx-reverse-proxy.yml

**Comment by kgnfth** [comment]
@sardaukar i have fixed it
the issue was you defined the PENPOT_DATABASE_URI and PENPOT_REDIS_URI values wrong

Demo: https://penpot.app.gocloud.fun/
click on `Create demo account`

```yaml
captainVersion: 4

services:
    $$cap_appname-db:
        image: 'postgres:13'
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_INITDB_ARGS: --data-checksums
            POSTGRES_DB: penpot
            POSTGRES_USER: penpot
            POSTGRES_PASSWORD: penpot
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-redis:
        image: 'redis:6'
        restart: always
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-exporter:
        image: 'penpotapp/exporter:1.1.0-alpha'
        restart: always
        environment:
            PENPOT_PUBLIC_URI: $$cap_public_uri
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-backend:
        image: 'penpotapp/backend:1.1.0-alpha'
        volumes:
            - $$cap_appname-assets-data:/opt/data
        environment:
            PENPOT_PUBLIC_URI: $$cap_public_uri
            PENPOT_TELEMETRY_ENABLED: 'false' # no one wants this enabled anyway
            PENPOT_SMTP_DEFAULT_FROM: $$cap_smtp_from
            PENPOT_SMTP_DEFAULT_REPLY_TO: $$cap_smtp_reply_to
            PENPOT_SMTP_HOST: $$cap_smtp_host
            PENPOT_SMTP_PORT: $$cap_smtp_port
            PENPOT_SMTP_USERNAME: $$cap_smtp_username
            PENPOT_SMTP_PASSWORD: $$cap_smtp_password
            PENPOT_SMTP_TLS: $$cap_smtp_tls
            PENPOT_SMTP_SSL: $$cap_smtp_ssl

            PENPOT_DATABASE_URI: postgresql://srv-captain--$$cap_appname-db/penpot
            PENPOT_DATABASE_USERNAME: penpot
            PENPOT_DATABASE_PASSWORD: penpot
            PENPOT_REDIS_URI: redis://srv-captain--$$cap_appname-redis:6379/0
            PENPOT_STORAGE_BACKEND: fs
            PENPOT_STORAGE_FS_DIRECTORY: /opt/data/assets
            PENPOT_SMTP_ENABLED: 'true'
        depends_on:
            - $$cap_appname-db
            - $$cap_appname-redis
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname:
        volumes:
            - $$cap_appname-assets-data:/opt/data
        caproverExtra:
            dockerfileLines:
                - FROM penpotapp/frontend:1.1.0-alpha
                - RUN sed -i 's/penpot-backend/srv-captain--$$cap_appname-backend/g' /etc/nginx/nginx.conf
                - RUN sed -i 's/penpot-exporter/srv-captain--$$cap_appname-exporter/g' /etc/nginx/nginx.conf
        depends_on:
            - $$cap_appname-backend
            - $$cap_appname-exporter

caproverOneClickApp:
    variables:
        - id: $$cap_public_uri
          label: Public URI
          defaultValue: https://penpot
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_from
          label: STMP from address
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_reply_to
          label: STMP reply address
          defaultValue: no-reply@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_host
          label: STMP host
          defaultValue: smtp.example.com
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_port
          label: STMP port
          defaultValue: 587
          validRegex: /^^((6553[0-5])|(655[0-2][0-9])|(65[0-4][0-9]{2})|(6[0-4][0-9]{3})|([1-5][0-9]{4})|([0-5]{0,5})|([0-9]{1,4}))$$/
        - id: $$cap_smtp_username
          label: STMP username
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_password
          label: STMP password
          defaultValue:
          validRegex: /.{1,}/
        - id: $$cap_smtp_tls
          label: STMP TLS support
          defaultValue: true
          validRegex: /^(true|false)$/
        - id: $$cap_smtp_ssl
          label: STMP SSL support
          defaultValue: false
          validRegex: /^(true|false)$/
    instructions:
        start: >-
            The open-source solution for design and prototyping.
        end: >
            Penpot is deployed and available as $$cap_appname. IMPORTANT: It will take up to 2 minutes for Penpot to be ready. Before that, you might see a 502 error page.
    displayName: Penpot
    isOfficial: true
    description: The open-source solution for design and prototyping.
    documentation: Official docs are [here](https://github.com/penpot/penpot/tree/develop/docs)

```

**Comment by kgnfth** [comment]
@sardaukar i have fixed it
the issue was you defined the PENPOT_DATABASE_URI and PENPOT_REDIS_URI values wrong

Demo: https://penpot.app.gocloud.fun/
click on `Create demo account` or create an account 😋

```yaml
captainVersion: 4

services:
    $$cap_appname-postgres:
        image: postgres:$$cap_postgres_version
        volumes:
            - $$cap_appname-postgres-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_INITDB_ARGS: --data-checksums
            POSTGRES_DB: penpot
            POSTGRES_USER: penpot
            POSTGRES_PASSWORD: $$cap_postgres_pass
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-redis:
        image: redis:$$cap_redis_version
        restart: always
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-exporter:
        image: penpotapp/exporter:$$cap_penpot_exporter_version
        restart: always
        environment:
            PENPOT_PUBLIC_URI: $$cap_public_uri
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-backend:
        image: penpotapp/backend:$$cap_penpot_backend_version
        volumes:
            - $$cap_appname-assets-data:/opt/data
        environment:
            PENPOT_PUBLIC_URI: $$cap_public_uri
            PENPOT_TELEMETRY_ENABLED: $$cap_enable_telemetry
            PENPOT_SMTP_DEFAULT_FROM: $$cap_smtp_from
            PENPOT_SMTP_DEFAULT_REPLY_TO: $$cap_smtp_reply_to
            PENPOT_SMTP_HOST: $$cap_smtp_host
            PENPOT_SMTP_PORT: $$cap_smtp_port
            PENPOT_SMTP_USERNAME: $$cap_smtp_username
            PENPOT_SMTP_PASSWORD: $$cap_smtp_password
            PENPOT_SMTP_TLS: $$cap_smtp_tls
            PENPOT_SMTP_SSL: $$cap_smtp_ssl

            PENPOT_DATABASE_URI: postgresql://srv-captain--$$cap_appname-postgres/penpot
            PENPOT_DATABASE_USERNAME: penpot
            PENPOT_DATABASE_PASSWORD: $$cap_postgres_pass
            PENPOT_REDIS_URI: redis://srv-captain--$$cap_appname-redis:6379/0
            PENPOT_STORAGE_BACKEND: fs
            PENPOT_STORAGE_FS_DIRECTORY: /opt/data/assets
            PENPOT_SMTP_ENABLED: 'true'
        depends_on:
            - $$cap_appname-postgres
            - $$cap_appname-redis
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname:
        volumes:
            - $$cap_appname-assets-data:/opt/data
        caproverExtra:
            dockerfileLines:
                - FROM penpotapp/frontend:$$cap_penpot_frontend_version
                - RUN sed -i 's/penpot-backend/srv-captain--$$cap_appname-backend/g' /etc/nginx/nginx.conf
                - RUN sed -i 's/penpot-exporter/srv-captain--$$cap_appname-exporter/g' /etc/nginx/nginx.conf
        depends_on:
            - $$cap_appname-backend
            - $$cap_appname-exporter

caproverOneClickApp:
    variables:
        - id: $$cap_postgres_version
          label: Postgres Version
          defaultValue: '13'
          description: Checkout their docker description page for the valid tags https://hub.docker.com/r/lycheeorg/lychee/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_redis_version
          label: Redis Version
          defaultValue: '6'
          description: Checkout their docker desctiption page for the valid tags https://hub.docker.com/_/redis?tab=description
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_penpot_frontend_version
          label: Penpot Frontend Version
          defaultValue: '1.1.0-alpha'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/penpotapp/frontend/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_penpot_backend_version
          label: Penpot Backend Version
          defaultValue: '1.1.0-alpha'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/penpotapp/backend/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_penpot_exporter_version
          label: Penpot Exporter Version
          defaultValue: '1.1.0-alpha'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/penpotapp/exporter/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_pass
          label: Potgress Database password
          description: 'Pasword for postgres'
          validRegex: /.{1,}/
        - id: $$cap_public_uri
          label: Public URI
          defaultValue: https://penpot
          description: 'Frontend url to access your Penpot'
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_from
          label: STMP from address
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_reply_to
          label: STMP reply address
          defaultValue: no-reply@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_host
          label: STMP host
          defaultValue: smtp.example.com
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_port
          label: STMP port
          defaultValue: 587
          validRegex: /^^((6553[0-5])|(655[0-2][0-9])|(65[0-4][0-9]{2})|(6[0-4][0-9]{3})|([1-5][0-9]{4})|([0-5]{0,5})|([0-9]{1,4}))$$/
        - id: $$cap_smtp_username
          label: STMP username
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_password
          label: STMP password
          defaultValue:
          validRegex: /.{1,}/
        - id: $$cap_smtp_tls
          label: STMP TLS support
          defaultValue: true
          validRegex: /^(true|false)$/
        - id: $$cap_smtp_ssl
          label: STMP SSL support
          defaultValue: false
          validRegex: /^(true|false)$/
        - id: $$cap_enable_telemetry
          label: Send Anonymous Data
          description: When enabled, a periodical process will send annonymous data about this instance. Read more at https://github.com/penpot/penpot/blob/f2fd97693427c7decb86e745bf178fe70fe332a0/docker/images/docker-compose.yaml#L56-L62
          defaultValue: false
          validRegex: /^(true|false)$/
          
    instructions:
        start: >-
            The open-source solution for design and prototyping.
        end: >
            Penpot is deployed and available as http://$$cap_appname.$$cap_root_domain. IMPORTANT: It will take up to 2 minutes for Penpot to be ready. Before that, you might see a 502 error page.
    displayName: Penpot
    isOfficial: true # it is Penpot's official image
    description: The open-source solution for design and prototyping.
    documentation: Official docs are [here](https://github.com/penpot/penpot/tree/develop/docs)
```

**Comment by kgnfth** [comment]
Bump. 😋

**Comment by githubsaturn** [comment]
@kgnfth  - want to close this PR and open a clean PR?

**Comment by kgnfth** [comment]
@githubsaturn Yes pls. i will send a pr, as soon as i tested everything !

**Pull request closed without merging**
